$basePath = "C:\Cloude\registry\lexemes"
$date = "2026-07-16"

$entries = @()

# ====== SECTION 3: L-000301 to L-000450 ======
# Verbs, adjectives, grammatical particles

# ---- L-000301 to L-000330: Verb roots (-o form, present tense / action nominal) ----
$entries += @{id="L-000301"; lex="talo"; root=$false; pos="глагол"; trans="говорить, речь"; etym="Новый корень tal- (говорение) + -o (действие)"; ex1="Tale talu thero."; ex1t="Говорящий произносит слово."; ex2="Xha-ruun talo sha-ruun."; ex2t="Разумный народ говорит на своём языке."; deriv="tala, tale, tali, talu, talae"}
$entries += @{id="L-000302"; lex="mero"; root=$false; pos="глагол"; trans="видеть, смотреть, взгляд"; etym="Корень mer- (зрение) + -o (действие)"; ex1="Mero thali khar-thal."; ex1t="Видит горизонт в рассвете."; ex2="Xhare mero ven-sha."; ex2t="Мыслитель видит истину."; deriv="mera, mere, meri, meru, merae"}
$entries += @{id="L-000303"; lex="feno"; root=$false; pos="глагол"; trans="расти, развиваться"; etym="Корень fen- (рост) + -o (действие)"; ex1="Xare feno mori."; ex1t="Существо растёт в воде."; ex2="Ruun feno veni."; ex2t="Народ растёт через знание."; deriv="fena, fene, feni, fenu, fenae"}
$entries += @{id="L-000304"; lex="kalo"; root=$false; pos="глагол"; trans="делать, создавать, творить"; etym="Корень kal- (творение) + -o (действие)"; ex1="Vashe kalo ruuni."; ex1t="Строитель создаёт поселение."; ex2="Xhare kalo shari."; ex2t="Мыслитель создаёт словарь."; deriv="kala, kale, kali, kalu, kalae"}
$entries += @{id="L-000305"; lex="reno"; root=$false; pos="глагол"; trans="идти, двигаться, странствовать"; etym="Корень ren- (движение) + -o (действие)"; ex1="Rasse reno thal-rass."; ex1t="Странник идёт по космосу."; ex2="Reno kel-ver thali."; ex2t="Идёт к горам на горизонте."; deriv="rena, rene, reni, renu, renae"}
$entries += @{id="L-000306"; lex="baro"; root=$false; pos="глагол"; trans="защищать, оберегать"; etym="Корень bar- (защита) + -o (действие)"; ex1="Vokhre baro ruuni."; ex1t="Страж защищает поселение."; ex2="Xha-ruun baro veni."; ex2t="Народ оберегает знание."; deriv="bara, bare, bari, bar u, barrae"}
$entries += @{id="L-000307"; lex="gatho"; root=$false; pos="глагол"; trans="собирать, объединять"; etym="Корень gath- (сбор) + -o (действие)"; ex1="Ruune gatho ruuno."; ex1t="Члены собираются на собрание."; ex2="Gatho thel veni."; ex2t="Собирает архив знаний."; deriv="gatha, gathe, gathi, gathu, gathae"}
$entries += @{id="L-000308"; lex="delo"; root=$false; pos="глагол"; trans="резать, разделять"; etym="Корень del- (деление) + -o (действие)"; ex1="Vashe delo vash."; ex1t="Строитель режет камень."; ex2="Delo the-rass theri."; ex2t="Разделяет равнину надвое."; deriv="dela, dele, deli, delu, delae"}
$entries += @{id="L-000309"; lex="sono"; root=$false; pos="глагол"; trans="звучать, петь, издавать звук"; etym="Корень son- (звук) + -o (действие)"; ex1="Share sono sha-ruun."; ex1t="Сказитель поёт на языке народа."; ex2="Zhalo sono thali."; ex2t="Ветер поёт у горизонта."; deriv="sona, sone, soni, sonu, sonae"}
$entries += @{id="L-000310"; lex="pasho"; root=$false; pos="глагол"; trans="писать, чертить, записывать"; etym="Корень pash- (письмо) + -o (действие)"; ex1="Vene pasho veni."; ex1t="Мудрец пишет в архиве."; ex2="Pasho vash-ven theri."; ex2t="Пишет истину на камне."; deriv="pasha, pashe, pashi, pashu, pashae"}
$entries += @{id="L-000311"; lex="thulo"; root=$false; pos="глагол"; trans="строить, возводить, созидать"; etym="Корень thul- (строение) + -o (действие)"; ex1="Vashe thulo ruuni."; ex1t="Строитель возводит поселение."; ex2="Ruun thulo vokhri."; ex2t="Народ строит храм."; deriv="thula, thule, thuli, thulu, thulae"}
$entries += @{id="L-000312"; lex="rimo"; root=$false; pos="глагол"; trans="течь, литься, струиться"; etym="Корень rim- (течение) + -o (действие)"; ex1="Mor rimo veri."; ex1t="Вода течёт по скале."; ex2="Moro rimo mor-thal."; ex2t="Течение струится в океан."; deriv="rima, rime, rimi, rimu, rimae"}
$entries += @{id="L-000313"; lex="nasho"; root=$false; pos="глагол"; trans="открывать, находить"; etym="Корень nash- (открытие) + -o (действие)"; ex1="Rasse nasho rassi."; ex1t="Странник открывает портал."; ex2="Xha-ruun nasho ven."; ex2t="Народ открывает истину."; deriv="nasha, nashe, nashi, nashu, nashae"}
$entries += @{id="L-000314"; lex="hosho"; root=$false; pos="глагол"; trans="чувствовать, ощущать"; etym="Корень hosh- (чувство) + -o (действие)"; ex1="Xare hosho kossa."; ex1t="Существо чувствует холод."; ex2="Xha-ruun hosho vokhra."; ex2t="Народ чувствует гармонию."; deriv="hosha, hoshe, hoshi, hosh u, hoshae"}
$entries += @{id="L-000315"; lex="vilo"; root=$false; pos="глагол"; trans="желать, стремиться, хотеть"; etym="Корень vil- (желание) + -o (действие)"; ex1="Xhare vilo veno."; ex1t="Мыслитель желает познания."; ex2="Ruun vilo mor-thal."; ex2t="Народ стремится к океану."; deriv="vila, vile, vili, vilu, vilae"}
$entries += @{id="L-000316"; lex="kero"; root=$false; pos="глагол"; trans="гореть, сиять, излучать"; etym="Корень ker- (горение) + -o (действие)"; ex1="Khar-vex kero thali."; ex1t="Звезда горит на горизонте."; ex2="Koss-thal kero ser-thal."; ex2t="Полярное сияние горит в ночи."; deriv="kera, kere, keri, keru, kerae"}
$entries += @{id="L-000317"; lex="lasho"; root=$false; pos="глагол"; trans="падать, опускаться, ниспадать"; etym="Корень lash- (падение) + -o (действие)"; ex1="Mor-ver lasho veri."; ex1t="Водопад низвергается со скалы."; ex2="Kharu lasho thali."; ex2t="Луч падает к горизонту."; deriv="lasha, lashe, lashi, lashu, lashae"}
$entries += @{id="L-000318"; lex="bemo"; root=$false; pos="глагол"; trans="терять, забывать"; etym="Корень bem- (утрата) + -o (действие)"; ex1="Bemo thel ven."; ex1t="Забывает истину."; ex2="Ruun bemo sha-ruun?"; ex2t="Народ теряет язык?"; deriv="bema, beme, bemi, bemu, bemrae"}
$entries += @{id="L-000319"; lex="runo"; root=$false; pos="глагол"; trans="бежать, спешить, мчаться"; etym="Корень run- (бег) + -o (действие)"; ex1="Zhal-vex runo thali."; ex1t="Ветер мчится к горизонту."; ex2="Rune runo ruuni."; ex2t="Гонец бежит в поселение."; deriv="runa, rune, runi, runu, runae"}
$entries += @{id="L-000320"; lex="zovo"; root=$false; pos="глагол"; trans="вращать, крутить, поворачивать"; etym="Корень zov- (вращение) + -o (действие)"; ex1="Ser zovo theri."; ex1t="Луна вращается вокруг земли."; ex2="Vex-ser zovo mor-thal."; ex2t="Прилив вращает океан."; deriv="zova, zove, zovi, zovu, zovae"}
$entries += @{id="L-000321"; lex="quino"; root=$false; pos="глагол"; trans="просить, умолять, вопрошать"; etym="Корень quin- (просьба) + -o (действие)"; ex1="Ruune quino ven."; ex1t="Член общины просит истины."; ex2="Xhare quino xharu."; ex2t="Мыслитель вопрошает идею."; deriv="quina, quine, quini, quinu, quinae"}
$entries += @{id="L-000322"; lex="tasho"; root=$false; pos="глагол"; trans="ударять, бить, стучать"; etym="Корень tash- (удар) + -o (действие)"; ex1="Vex-thal tasho theri."; ex1t="Молния ударяет в землю."; ex2="Mor tasho veri."; ex2t="Волна бьёт о скалу."; deriv="tasha, tashe, tashi, tashu, tashae"}
$entries += @{id="L-000323"; lex="maro"; root=$false; pos="глагол"; trans="держать, владеть, иметь"; etym="Корень mar- (владение) + -o (действие)"; ex1="Ruun maro vena."; ex1t="Народ владеет истиной."; ex2="Xha-ruun maro shara."; ex2t="Разумный народ имеет язык."; deriv="mara, mare, mari, maru, marae"}
$entries += @{id="L-000324"; lex="vesho"; root=$false; pos="глагол"; trans="покрывать, накрывать, укрывать"; etym="Корень vesh- (покров) + -o (действие)"; ex1="Zhal-mor vesho theri."; ex1t="Туман покрывает землю."; ex2="Koss vesho kel-ver."; ex2t="Лёд покрывает горы."; deriv="vesha, veshe, veshi, veshu, veshae"}
$entries += @{id="L-000325"; lex="solo"; root=$false; pos="глагол"; trans="плавать, плыть"; etym="Корень sol- (плавание) + -o (действие)"; ex1="More solo mor-thal."; ex1t="Моряк плывёт по океану."; ex2="Mor-koss solo mori."; ex2t="Айсберг плывёт в воде."; deriv="sola, sole, soli, solu, solae"}
$entries += @{id="L-000326"; lex="kedo"; root=$false; pos="глагол"; trans="кусать, жевать, грызть"; etym="Корень ked- (кусание) + -o (действие)"; ex1="Xare kedo xari."; ex1t="Существо жуёт пищу среды."; ex2="Mor-vash kedo vash."; ex2t="Волна грызёт камень."; deriv="keda, kede, kedi, kedu, kedae"}
$entries += @{id="L-000327"; lex="niro"; root=$false; pos="глагол"; trans="исчезать, таять, растворяться"; etym="Корень nir- (исчезновение) + -o (действие)"; ex1="Koss niro thel."; ex1t="Лёд исчезает в тепле."; ex2="Ser-thal niro kharu."; ex2t="Ночь исчезает с лучом."; deriv="nira, nire, niri, niru, nirae"}
$entries += @{id="L-000328"; lex="bosho"; root=$false; pos="глагол"; trans="ломать, разрушать"; etym="Корень bosh- (разрушение) + -o (действие)"; ex1="Vex thel bosho vash."; ex1t="Сила ломает камень."; ex2="Zhal bosho veri."; ex2t="Ветер разрушает скалу."; deriv="bosha, bosh e, boshi, boshu, boshae"}
$entries += @{id="L-000329"; lex="gralo"; root=$false; pos="глагол"; trans="глотать, поглощать, вбирать"; etym="Корень gral- (поглощение) + -o (действие)"; ex1="The gralo mor."; ex1t="Земля поглощает воду."; ex2="Xhari gralo xharu."; ex2t="Разум вбирает идею."; deriv="grala, grale, grali, gralu, gralae"}
$entries += @{id="L-000330"; lex="zamo"; root=$false; pos="глагол"; trans="знать, понимать, постигать"; etym="Корень zam- (знание/понимание) + -o (действие)"; ex1="Vene zamo ven."; ex1t="Мудрец знает истину."; ex2="Xha-ruun zamo thel-rass."; ex2t="Народ понимает мир."; deriv="zama, zame, zami, zamu, zamae"}

# ---- L-000331 to L-000350: Past and future tenses, imperatives ----
$entries += @{id="L-000331"; lex="talel"; root=$false; pos="глагол, прош. вр."; trans="говорил, сказал"; etym="Корень tal- + -el (прошедшее время)"; ex1="Vene talel ven."; ex1t="Мудрец сказал истину."; ex2="Xhare talel sharu."; ex2t="Мыслитель изрёк слово."; deriv="talelae"}
$entries += @{id="L-000332"; lex="talun"; root=$false; pos="глагол, буд. вр."; trans="будет говорить, скажет"; etym="Корень tal- + -un (будущее время)"; ex1="Vene talun ven."; ex1t="Мудрец скажет истину."; ex2="Ruun talun sha-ruun."; ex2t="Народ заговорит на своём языке."; deriv="talunae"}
$entries += @{id="L-000333"; lex="merel"; root=$false; pos="глагол, прош. вр."; trans="видел, узрел"; etym="Корень mer- + -el (прошедшее время)"; ex1="Rasse merel rassi."; ex1t="Странник видел портал."; ex2="Xhare merel khar-ven."; ex2t="Мыслитель узрел озарение."; deriv="merelae"}
$entries += @{id="L-000334"; lex="merun"; root=$false; pos="глагол, буд. вр."; trans="увидит, узрит"; etym="Корень mer- + -un (будущее время)"; ex1="Ruune merun thal-rass."; ex1t="Член общины узрит космос."; ex2="Vene merun vena."; ex2t="Мудрец увидит истину."; deriv="merunae"}
$entries += @{id="L-000335"; lex="fenel"; root=$false; pos="глагол, прош. вр."; trans="рос, развивался"; etym="Корень fen- + -el (прошедшее время)"; ex1="Xari fenel mori."; ex1t="Биом рос у воды."; ex2="Ruun fenel veni."; ex2t="Народ развивался через знание."; deriv="fenelae"}
$entries += @{id="L-000336"; lex="kelan"; root=$false; pos="глагол, повелит."; trans="восходи!, поднимись!"; etym="Корень kel- + -an (повелительное наклонение)"; ex1="Kelan veri!"; ex1t="Восходи на скалу!"; ex2="Kelan keli!"; ex2t="Поднимись на вершину!"; deriv="kelanxare"}
$entries += @{id="L-000337"; lex="talan"; root=$false; pos="глагол, повелит."; trans="говори!, скажи!"; etym="Корень tal- + -an (повелительное наклонение)"; ex1="Talan ven-sha!"; ex1t="Говори правду!"; ex2="Talan sha-ruun!"; ex2t="Скажи на языке народа!"; deriv="talanshare"}
$entries += @{id="L-000338"; lex="meran"; root=$false; pos="глагол, повелит."; trans="смотри!, виждь!"; etym="Корень mer- + -an (повелительное наклонение)"; ex1="Meran thali!"; ex1t="Смотри на горизонт!"; ex2="Meran khar-thal!"; ex2t="Виждь рассвет!"; deriv="meranxhare"}
$entries += @{id="L-000339"; lex="delir"; root=$false; pos="глагол, условн."; trans="разделил бы, если бы разделил"; etym="Корень del- + -ir (условное наклонение)"; ex1="Delir the-rass, xari fenun."; ex1t="Если бы разделил равнину, биом бы рос."; ex2="Delir vash, ruun thulun."; ex2t="Если бы разделил камень, народ бы построил."; deriv="dilire"}
$entries += @{id="L-000340"; lex="renir"; root=$false; pos="глагол, условн."; trans="пошёл бы, если бы пошёл"; etym="Корень ren- + -ir (условное наклонение)"; ex1="Renir thali, rassi nashun."; ex1t="Если бы пошёл к горизонту, открыл бы портал."; ex2="Renir mor-thal, more felun."; ex2t="Если бы пошёл к океану, стал бы моряком."; deriv="renire"}

# ---- L-000341 to L-000350: Other verb forms ----
$entries += @{id="L-000341"; lex="kalel"; root=$false; pos="глагол, прош. вр."; trans="создал, сотворил"; etym="Корень kal- + -el (прошедшее время)"; ex1="Vokhre kalel ruuni."; ex1t="Хранитель создал поселение."; ex2="Xhare kalel shari."; ex2t="Мыслитель создал словарь."; deriv="kalelae"}
$entries += @{id="L-000342"; lex="thulun"; root=$false; pos="глагол, буд. вр."; trans="построит, возведёт"; etym="Корень thul- + -un (будущее время)"; ex1="Vashe thulun vokhri."; ex1t="Строитель возведёт храм."; ex2="Ruun thulun ruuni."; ex2t="Народ построит поселение."; deriv="thulunae"}
$entries += @{id="L-000343"; lex="rimel"; root=$false; pos="глагол, прош. вр."; trans="тёк, лился"; etym="Корень rim- + -el (прошедшее время)"; ex1="Mor rimel mor-ver."; ex1t="Вода текла водопадом."; ex2="Moro rimel the-rass."; ex2t="Поток лился по равнине."; deriv="rimelae"}
$entries += @{id="L-000344"; lex="rimun"; root=$false; pos="глагол, буд. вр."; trans="потечёт, польётся"; etym="Корень rim- + -un (будущее время)"; ex1="Mor rimun the-ver."; ex1t="Вода потечёт с горы."; ex2="Zhal-mor rimun thali."; ex2t="Туман польётся дождём."; deriv="rimunae"}
$entries += @{id="L-000345"; lex="hoshir"; root=$false; pos="глагол, условн."; trans="почувствовал бы"; etym="Корень hosh- + -ir (условное наклонение)"; ex1="Hoshir kossa, kharun merun."; ex1t="Если бы почувствовал холод, увидел бы сияние."; ex2="Hoshir vokhra, xha-ruun thulun."; ex2t="Если бы почувствовал гармонию, народ бы построил."; deriv="hoshiren"}
$entries += @{id="L-000346"; lex="baril"; root=$false; pos="глагол, пассив"; trans="быть защищённым, охраняться"; etym="Корень bar- + -il (пассивный залог)"; ex1="Ruuni baril vokhren."; ex1t="Поселение охраняется стражами."; ex2="Veni baril xha-ruunen."; ex2t="Архив защищается народом."; deriv="barilxare"}
$entries += @{id="L-000347"; lex="maril"; root=$false; pos="глагол, пассив"; trans="быть удерживаемым, храниться"; etym="Корень mar- + -il (пассивный залог)"; ex1="Ven maril xhari."; ex1t="Истина хранится в разуме."; ex2="Sha-ruun maril ruunen."; ex2t="Язык хранится народом."; deriv="marilvash"}
$entries += @{id="L-000348"; lex="sonel"; root=$false; pos="глагол, прош. вр."; trans="звучал, пел"; etym="Корень son- + -el (прошедшее время)"; ex1="Sha-mor sonel ruuni."; ex1t="Легенда звучала в народе."; ex2="Zhalo sonel thali."; ex2t="Ветер пел у горизонта."; deriv="sonelxari"}
$entries += @{id="L-000349"; lex="kalan"; root=$false; pos="глагол, повелит."; trans="делай!, твори!"; etym="Корень kal- + -an (повелительное наклонение)"; ex1="Kalan ruuni!"; ex1t="Создай поселение!"; ex2="Kalan shari!"; ex2t="Сотвори словарь!"; deriv="kalanvashe"}
$entries += @{id="L-000350"; lex="nashil"; root=$false; pos="глагол, пассив"; trans="быть открытым, открываться"; etym="Корень nash- + -il (пассивный залог)"; ex1="Rassi nashil xharun."; ex1t="Портал открывается идеей."; ex2="Ven nashil xharen."; ex2t="Истина открывается мыслителем."; deriv="nashilrassi"}

# ---- L-000351 to L-000370: Adjectives with -ae suffix ----
$entries += @{id="L-000351"; lex="talae"; root=$false; pos="прилагательное"; trans="словесный, устный"; etym="Корень tal- (говорение) + -ae (свойство)"; ex1="Talae sha-ruun thel shara."; ex1t="Устный язык — это речь."; ex2="Talae xharu thel sharu."; ex2t="Словесная идея — высказывание."; deriv="talaexari"}
$entries += @{id="L-000352"; lex="merae"; root=$false; pos="прилагательное"; trans="зримый, видимый, очевидный"; etym="Корень mer- (зрение) + -ae (свойство)"; ex1="Merae khar-vex thali thero."; ex1t="Зримая звезда на горизонте."; ex2="Merae ven thel khar-ven."; ex2t="Очевидная истина — озарение."; deriv="meraekhar"}
$entries += @{id="L-000353"; lex="fenae"; root=$false; pos="прилагательное"; trans="растущий, развивающийся"; etym="Корень fen- (рост) + -ae (свойство)"; ex1="Fenae xari thel the-mor."; ex1t="Растущий биом — болото."; ex2="Fenae ruun thel xha-ruun."; ex2t="Растущий народ — цивилизация."; deriv="fenaethal"}
$entries += @{id="L-000354"; lex="kalae"; root=$false; pos="прилагательное"; trans="творческий, созидательный"; etym="Корень kal- (творение) + -ae (свойство)"; ex1="Kalae xhare thel vashe."; ex1t="Творческий мыслитель — строитель."; ex2="Kalae ruun thulo vokhri."; ex2t="Созидательный народ строит храм."; deriv="kalaexha"}
$entries += @{id="L-000355"; lex="renae"; root=$false; pos="прилагательное"; trans="движущийся, мобильный"; etym="Корень ren- (движение) + -ae (свойство)"; ex1="Renae ruun thel zhal-ruun."; ex1t="Движущийся народ — кочевники."; ex2="Renae xari thel mor-thal."; ex2t="Подвижная среда — океан."; deriv="renaerass"}
$entries += @{id="L-000356"; lex="barrae"; root=$false; pos="прилагательное"; trans="защитный, охраняющий"; etym="Корень bar- (защита) + -rae (свойство)"; ex1="Barrae vokhre ruuni theri."; ex1t="Защитный страж у поселения."; ex2="Barrae vash thel ruuni."; ex2t="Защитный камень — стена."; deriv="barraevash"}
$entries += @{id="L-000357"; lex="gathae"; root=$false; pos="прилагательное"; trans="сборный, объединённый"; etym="Корень gath- (сбор) + -ae (свойство)"; ex1="Gathae ruun thel ruuna."; ex1t="Объединённый народ — общность."; ex2="Gathae ven thel veni."; ex2t="Сборное знание — архив."; deriv="gathaexari"}
$entries += @{id="L-000358"; lex="sonae"; root=$false; pos="прилагательное"; trans="звучный, мелодичный"; etym="Корень son- (звук) + -ae (свойство)"; ex1="Sonae sha-mor ruuni thero."; ex1t="Звучная легенда живёт в народе."; ex2="Sonae zhalo thali thero."; ex2t="Мелодичный ветер у горизонта."; deriv="sonaexhare"}
$entries += @{id="L-000359"; lex="pashae"; root=$false; pos="прилагательное"; trans="письменный, записанный"; etym="Корень pash- (письмо) + -ae (свойство)"; ex1="Pashae sha-ruun veni theri."; ex1t="Письменный язык в архиве."; ex2="Pashae ven thel vash-ven."; ex2t="Записанная истина — каменное слово."; deriv="pashaekhar"}
$entries += @{id="L-000360"; lex="thulae"; root=$false; pos="прилагательное"; trans="строительный, архитектурный"; etym="Корень thul- (строение) + -ae (свойство)"; ex1="Thulae vash thel ruuni."; ex1t="Строительный камень — основа."; ex2="Thulae vokhri thel vashi."; ex2t="Архитектурный храм — здание."; deriv="thulaevashe"}

$entries += @{id="L-000361"; lex="rimae"; root=$false; pos="прилагательное"; trans="текучий, жидкий"; etym="Корень rim- (течение) + -ae (свойство)"; ex1="Rimae mor thel xaro."; ex1t="Текучая вода — жизнь."; ex2="Rimae moro thel mori."; ex2t="Жидкий поток — в водоёме."; deriv="rimaemor"}
$entries += @{id="L-000362"; lex="nashae"; root=$false; pos="прилагательное"; trans="открытый, доступный"; etym="Корень nash- (открытие) + -ae (свойство)"; ex1="Nashae rassi thel ven."; ex1t="Открытый портал ведёт к знанию."; ex2="Nashae xhari thel thali."; ex2t="Открытый разум — горизонт."; deriv="nashaethal"}
$entries += @{id="L-000363"; lex="virae"; root=$false; pos="прилагательное"; trans="желанный, вожделенный"; etym="Корень vil- (желание) + -ae (свойство)"; ex1="Virae ven thel xharu."; ex1t="Желанная истина — идея."; ex2="Virae mori thel xari."; ex2t="Желанный водоём — среда."; deriv="viraexari"}
$entries += @{id="L-000364"; lex="kerae"; root=$false; pos="прилагательное"; trans="горящий, сияющий"; etym="Корень ker- (горение) + -ae (свойство)"; ex1="Kerae khar-vex thali thero."; ex1t="Горящая звезда на небе."; ex2="Kerae xhel thel vexi."; ex2t="Сияющий жар — источник."; deriv="keraekhar"}
$entries += @{id="L-000365"; lex="lashae"; root=$false; pos="прилагательное"; trans="ниспадающий, падающий"; etym="Корень lash- (падение) + -ae (свойство)"; ex1="Lashae mor-ver thel kharu."; ex1t="Ниспадающий водопад — свет."; ex2="Lashae kossi thel moro."; ex2t="Падающий лёд — ручей."; deriv="lashaexari"}
$entries += @{id="L-000366"; lex="kossae"; root=$false; pos="прилагательное"; trans="холодный, ледяной"; etym="Корень koss- (лёд) + -ae (свойство)"; ex1="Kossae mor thel koss-mor."; ex1t="Холодная вода — ледник."; ex2="Kossae zhal thel koss-zhal."; ex2t="Холодный воздух — мороз."; deriv="kossaekossi"}
$entries += @{id="L-000367"; lex="xhelae"; root=$false; pos="прилагательное"; trans="горячий, жаркий"; etym="Корень xhel- (жар) + -ae (свойство)"; ex1="Xhelae the thel xhel-the."; ex1t="Горячая земля — пустыня."; ex2="Xhelae xhel-zhal thel thali."; ex2t="Жаркий воздух — у горизонта."; deriv="xhelaexari"}
$entries += @{id="L-000368"; lex="vexae"; root=$false; pos="прилагательное"; trans="сильный, мощный"; etym="Корень vex- (сила) + -ae (свойство)"; ex1="Vexae tho-ruun thel ruun-vex."; ex1t="Сильный народ — это мощь."; ex2="Vexae moro thel mor-vex."; ex2t="Мощное течение — гидросила."; deriv="vexaevokh"}
$entries += @{id="L-000369"; lex="vokhrae"; root=$false; pos="прилагательное"; trans="гармоничный, упорядоченный"; etym="Корень vokh- (порядок) + -rae (свойство)"; ex1="Vokhrae ruun thel ruuna."; ex1t="Гармоничный народ — единство."; ex2="Vokhrae vokhri thel veni."; ex2t="Упорядоченный храм — архив."; deriv="vokhraexari"}
$entries += @{id="L-000370"; lex="xharae"; root=$false; pos="прилагательное"; trans="разумный, ментальный"; etym="Корень xha- (разум) + -rae (свойство)"; ex1="Xharae xhare thel vene."; ex1t="Разумный мыслитель — мудрец."; ex2="Xharae ruun thel xha-ruun."; ex2t="Разумный народ — цивилизация."; deriv="xharaeruun"}

$entries += @{id="L-000371"; lex="ruunae"; root=$false; pos="прилагательное"; trans="общинный, народный"; etym="Корень ruun- (народ) + -ae (свойство)"; ex1="Ruunae sha thel sha-ruun."; ex1t="Народный язык — наречие."; ex2="Ruunae vokhri thel ruuni."; ex2t="Общинный храм — в поселении."; deriv="ruunaexari"}
$entries += @{id="L-000372"; lex="kharae"; root=$false; pos="прилагательное"; trans="светлый, светящийся"; etym="Корень khar- (свет) + -ae (свойство)"; ex1="Kharae khar-thal thel thali."; ex1t="Светлый рассвет — в небе."; ex2="Kharae xharu thel khar-ven."; ex2t="Светлая идея — озарение."; deriv="kharaexha"}
$entries += @{id="L-000373"; lex="venae"; root=$false; pos="прилагательное"; trans="истинный, правильный"; etym="Корень ven- (истина) + -ae (свойство)"; ex1="Venae sha thel ven-sha."; ex1t="Истинное слово — правда."; ex2="Venae ven thel vena."; ex2t="Истинное знание — достоверность."; deriv="venaexari"}
$entries += @{id="L-000374"; lex="morae"; root=$false; pos="прилагательное"; trans="водный, мокрый, влажный"; etym="Корень mor- (вода) + -ae (свойство)"; ex1="Morae xari thel the-mor."; ex1t="Водная среда — болото."; ex2="Morae zhal thel zhal-mor."; ex2t="Влажный воздух — туман."; deriv="moraexari"}
$entries += @{id="L-000375"; lex="therae"; root=$false; pos="прилагательное"; trans="земной, материальный"; etym="Корень the- (земля) + -rae (свойство)"; ex1="Therae ruun thel the-ruun."; ex1t="Земной народ — оседлый."; ex2="Therae vash thel the-vash."; ex2t="Земной камень — порода."; deriv="theraevash"}
$entries += @{id="L-000376"; lex="thalerae"; root=$false; pos="прилагательное"; trans="вдохновляющий"; etym="Корень thal- (небо) + -e (деят) + -rae (свойство)"; ex1="Thalerae xharu thel xha-thal."; ex1t="Вдохновляющая идея — мечта."; ex2="Thalerae thalo thel zhalo."; ex2t="Вдохновляющий полёт — ветер."; deriv="thaleraxhare"}
$entries += @{id="L-000377"; lex="xhelae"; root=$false; pos="прилагательное"; trans="жаркий, раскалённый"; etym="Корень xhel- (жар) + -ae (свойство)"; ex1="Xhelae the thel xhel-the."; ex1t="Жаркая земля — пустыня."; ex2="Xhelae xhel-zhal thel thali."; ex2t="Раскалённый воздух — миражи."; deriv="xhelaexari"}
$entries += @{id="L-000378"; lex="rassae"; root=$false; pos="прилагательное"; trans="пространный, обширный"; etym="Корень rass- (пространство) + -ae (свойство)"; ex1="Rassae the-rass thel rhuri."; ex1t="Обширная равнина — простор."; ex2="Rassae thal-rass thel rhura."; ex2t="Обширный космос — грандиозность."; deriv="rassaerhu"}
$entries += @{id="L-000379"; lex="serae"; root=$false; pos="прилагательное"; trans="цикличный, периодичный"; etym="Корень ser- (цикл) + -ae (свойство)"; ex1="Serae the-ser thel xaro."; ex1t="Цикличный сезон — жизнь."; ex2="Serae moro thel mor-ser."; ex2t="Периодичное течение — прилив."; deriv="seraexari"}
$entries += @{id="L-000380"; lex="koss-kelae"; root=$false; pos="прилагательное"; trans="заснеженный, ледяной (о вершине)"; etym="koss-kel (снежная вершина) + -ae (свойство)"; ex1="Koss-kelae veri thali thero."; ex1t="Заснеженный пик на горизонте."; ex2="Koss-kelae kel-ver thel kossi."; ex2t="Ледяной хребет — родина льда."; deriv="kosskelaekeli"}

# ---- L-000381 to L-000400: More adjectives ----
$entries += @{id="L-000381"; lex="morae"; root=$false; pos="прилагательное"; trans="мокрый, водянистый"; etym="Корень mor- (вода) + -ae"; ex1="Morae theri xari thero."; ex1t="Мокрая почва — среда."; ex2="Morae zhal thel zhal-mor."; ex2t="Влажный воздух — туман."; deriv="moraemor"}
$entries += @{id="L-000382"; lex="rhuae"; root=$false; pos="прилагательное"; trans="великий, огромный"; etym="Корень rhu- (великий) + -ae"; ex1="Rhuae khar-vex thel rhuri."; ex1t="Великая звезда — в просторе."; ex2="Rhuae mor-thal thel rhura."; ex2t="Великий океан — колоссальность."; deriv="rhuaethal"}
$entries += @{id="L-000383"; lex="thelae"; root=$false; pos="прилагательное"; trans="малый, незначительный"; etym="Корень thel- (малый) + -ae"; ex1="Thelae xare thel xari."; ex1t="Малое существо — в среде."; ex2="Thelae vash-kel thel theli."; ex2t="Малый пик — укрытие."; deriv="thelaexari"}
$entries += @{id="L-000384"; lex="kelae"; root=$false; pos="прилагательное"; trans="высокий, возвышенный"; etym="Корень kel- (высота) + -ae"; ex1="Kelae kel-ver thali thero."; ex1t="Высокий хребет в небе."; ex2="Kelae xharu thel xha-kel."; ex2t="Высокая идея — амбиция."; deriv="kelaexha"}
$entries += @{id="L-000385"; lex="sharae"; root=$false; pos="прилагательное"; trans="речевой, языковой"; etym="Корень sha- (слово) + -rae"; ex1="Sharae ruun thel sha-ruun."; ex1t="Речевой народ — языковой."; ex2="Sharae ven thel ven-sha."; ex2t="Речевая истина — правда."; deriv="sharaexha"}
$entries += @{id="L-000386"; lex="zhalae"; root=$false; pos="прилагательное"; trans="воздушный, газообразный"; etym="Корень zhal- (воздух) + -ae"; ex1="Zhalae zhali thel thal-zhal."; ex1t="Воздушный слой — атмосфера."; ex2="Zhalae xari thel zhali."; ex2t="Воздушная среда — атмосфера."; deriv="zhalaevex"}
$entries += @{id="L-000387"; lex="vashae"; root=$false; pos="прилагательное"; trans="каменный, твёрдый"; etym="Корень vash- (камень) + -ae"; ex1="Vashae vashi ruuni theri."; ex1t="Каменное здание в поселении."; ex2="Vashae the-ver thel veri."; ex2t="Твёрдое предгорье — скала."; deriv="vashaethul"}
$entries += @{id="L-000388"; lex="morverae"; root=$false; pos="прилагательное"; trans="ниспадающий, каскадный"; etym="mor-ver (водопад) + -ae"; ex1="Morverae moro thel kharu."; ex1t="Ниспадающий поток — луч."; ex2="Morverae keli thel mor-ver."; ex2t="Каскадная высота — водопад."; deriv="morveraexari"}
$entries += @{id="L-000389"; lex="ruunvee"; root=$false; pos="прилагательное"; trans="властный, державный"; etym="ruun-vex (власть) + -ae"; ex1="Ruunvee ruun thel vex-ruun."; ex1t="Властный народ — сила."; ex2="Ruunvee ruuni vokhri theri."; ex2t="Державное поселение — храм."; deriv="ruunveevex"}
$entries += @{id="L-000390"; lex="morthalae"; root=$false; pos="прилагательное"; trans="океанический, морской"; etym="mor-thal (океан) + -ae"; ex1="Morthalae xari thel mor-thal."; ex1t="Океаническая среда — море."; ex2="Morthalae more thel ruun-mor."; ex2t="Морской народ — мореходы."; deriv="morthalaexari"}

$entries += @{id="L-000391"; lex="fenae"; root=$false; pos="прилагательное"; trans="плодородный, цветущий"; etym="Корень fen- (рост) + -ae"; ex1="Fenae theri xari thero."; ex1t="Плодородная почва — жизнь."; ex2="Fenae ruun thel the-ruun."; ex2t="Цветущий народ — оседлый."; deriv="fenaether"}
$entries += @{id="L-000392"; lex="vexae"; root=$false; pos="прилагательное"; trans="мощный, энергичный"; etym="Корень vex- (сила) + -ae"; ex1="Vexae moro thel mor-vex."; ex1t="Мощное течение — сила воды."; ex2="Vexae ruun thel vex-ruun."; ex2t="Мощный народ — власть."; deriv="vexaevokh"}
$entries += @{id="L-000393"; lex="zhamae"; root=$false; pos="прилагательное"; trans="понятный, осмысленный"; etym="Корень zam- (понимание) + -ae"; ex1="Zamae sha thel ven-sha."; ex1t="Понятное слово — правда."; ex2="Zamae ven thel xharu."; ex2t="Осмысленное знание — идея."; deriv="zamaexhare"}
$entries += @{id="L-000394"; lex="kalelae"; root=$false; pos="прилагательное"; trans="сотворённый, рукотворный"; etym="kal- (творение) + -el (прош.) + -ae (св-во)"; ex1="Kalelae ruuni thel vashi."; ex1t="Сотворённое поселение — здание."; ex2="Kalelae vokhri thel veni."; ex2t="Рукотворный храм — архив."; deriv="kalelaethul"}
$entries += @{id="L-000395"; lex="renae"; root=$false; pos="прилагательное"; trans="подвижный, кочевой"; etym="Корень ren- (движение) + -ae"; ex1="Renae ruun thel zhal-ruun."; ex1t="Подвижный народ — кочевники."; ex2="Renae xari thel mor-thal."; ex2t="Подвижная среда — океан."; deriv="renaerass"}
$entries += @{id="L-000396"; lex="mornae"; root=$false; pos="прилагательное"; trans="глубинный, глубокий"; etym="Корень morn- (глубина) + -ae"; ex1="Mornae mor-thal thel vash-mor."; ex1t="Глубинный океан — морское дно."; ex2="Mornae xharu thel mor-xha."; ex2t="Глубокая идея — интуиция."; deriv="mornaexha"}
$entries += @{id="L-000397"; lex="zanae"; root=$false; pos="прилагательное"; trans="учёный, знающий"; etym="Корень zan- (знание) + -ae"; ex1="Zanae vene veni thero."; ex1t="Знающий мудрец — в архиве."; ex2="Zanae ruun thel ven-ruun."; ex2t="Учёный народ — знания."; deriv="zanaeven"}
$entries += @{id="L-000398"; lex="xhelae"; root=$false; pos="прилагательное"; trans="огненный, пламенный"; etym="Корень xhel- (жар/огонь) + -ae"; ex1="Xhelae the-xhel thel vexi."; ex1t="Огненный вулкан — источник."; ex2="Xhelae xhel-khar thel kerae."; ex2t="Пламенный пожар — сияние."; deriv="xhelaekhar"}
$entries += @{id="L-000399"; lex="tashae"; root=$false; pos="прилагательное"; trans="резкий, внезапный, ударный"; etym="Корень tash- (удар) + -ae"; ex1="Tashae vex-thal thel thali."; ex1t="Внезапная молния в небе."; ex2="Tashae moro thel mor-kel."; ex2t="Резкое течение — волна."; deriv="tashaexari"}
$entries += @{id="L-000400"; lex="hoshe"; root=$false; pos="прилагательное"; trans="чувствительный, эмпатичный"; etym="Корень hosh- (чувство) + -e (деятель) > hoshae"; ex1="Hoshae xhare mor-xha maro."; ex1t="Чуткий мыслитель владеет интуицией."; ex2="Hoshae ruun vokhra hosho."; ex2t="Чуткий народ чувствует гармонию."; deriv="hoshaexari"}

# ---- L-000401 to L-000430: Particles, prepositions, conjunctions ----
$entries += @{id="L-000401"; lex="thel"; root=$true; pos="частица-связка"; trans="быть, являться, есть"; etym="Праязыковая связка, основа предикации"; ex1="Khar-vex thel khar-vex."; ex1t="Звезда есть свет-сила."; ex2="Xha-ruun thel xha-ruun."; ex2t="Разумный народ есть разум-народ."; deriv="thele, theli"}
$entries += @{id="L-000402"; lex="nel"; root=$false; pos="частица отрицания"; trans="не, нет"; etym="Отрицательная частица, базовая"; ex1="Xha-ruun nel bemo sha."; ex1t="Разумный народ не забывает язык."; ex2="Nel maro vena."; ex2t="Не владеет истиной."; deriv="nelae, nelshara"}
$entries += @{id="L-000403"; lex="khe"; root=$false; pos="вопросительная частица"; trans="ли, ? (маркер вопроса)"; etym="Вопросительный маркер"; ex1="Xha-ruun khe veno?"; ex1t="Познаёт ли разумный народ?"; ex2="Khe khar-vex thali thero?"; ex2t="Звезда ли на горизонте?"; deriv="khesha"}
$entries += @{id="L-000404"; lex="zhe"; root=$false; pos="частица усиления"; trans="же, именно, ведь"; etym="Эмфатический маркер"; ex1="Xha-ruun zhe maro ven."; ex1t="Разумный народ именно владеет истиной."; ex2="Zhe thel vena!"; ex2t="Это же истина!"; deriv="zhesha"}
$entries += @{id="L-000405"; lex="eth"; root=$false; pos="показатель множественного числа"; trans="-ы, -и (множественное число)"; etym="Маркер множественности"; ex1="Ruun-eth thali mero."; ex1t="Народы видят горизонт."; ex2="Khar-vex-eth thel rhuri."; ex2t="Звёзды — простор."; deriv="ethruun, ethkhar"}
$entries += @{id="L-000406"; lex="ran"; root=$false; pos="показатель притяжательности"; trans="(чей-то), принадлежащий"; etym="Посессивный маркер"; ex1="Xha-ruun ran sha."; ex1t="Язык разумного народа."; ex2="Ruune ran ruuni."; ex2t="Поселение общинника."; deriv="ransha"}
$entries += @{id="L-000407"; lex="vel"; root=$false; pos="союз"; trans="и, а также"; etym="Соединительный союз"; ex1="Mor vel thel the."; ex1t="Вода и земля."; ex2="Khar vel vex thel khar-vex."; ex2t="Свет и сила — звезда."; deriv="velae"}
$entries += @{id="L-000408"; lex="tos"; root=$false; pos="союз"; trans="или, либо"; etym="Разделительный союз"; ex1="Mor tos the?"; ex1t="Вода или земля?"; ex2="Khar tos vex?"; ex2t="Свет или сила?"; deriv="tosae"}
$entries += @{id="L-000409"; lex="khal"; root=$false; pos="предлог"; trans="в, внутри, на"; etym="Предлог местоположения"; ex1="Xare khal mori."; ex1t="Существо в воде."; ex2="Ruun khal ruuni."; ex2t="Народ в поселении."; deriv="khalsha"}
$entries += @{id="L-000410"; lex="mosh"; root=$false; pos="предлог"; trans="с, вместе с"; etym="Предлог совместности"; ex1="Ruune mosh xhare."; ex1t="Общинник с мыслителем."; ex2="Ren mosh mor."; ex2t="Идти с водой."; deriv="moshae"}

$entries += @{id="L-000411"; lex="thon"; root=$false; pos="предлог"; trans="через, сквозь"; etym="Предлог перемещения сквозь"; ex1="Ren thon the-rass."; ex1t="Идти через равнину."; ex2="Mero thon thali."; ex2t="Видеть сквозь горизонт."; deriv="thonae"}
$entries += @{id="L-000412"; lex="khom"; root=$false; pos="предлог"; trans="из, от, с (откуда)"; etym="Предлог происхождения"; ex1="Khar-vex khom thal-rass."; ex1t="Звезда из космоса."; ex2="Share khom ruuni."; ex2t="Cказитель из поселения."; deriv="khomae"}
$entries += @{id="L-000413"; lex="tael"; root=$false; pos="предлог"; trans="к, по направлению к"; etym="Предлог направления"; ex1="Ren tael thali."; ex1t="Идти к горизонту."; ex2="Mero tael khar-thal."; ex2t="Смотреть на рассвет."; deriv="taelae"}
$entries += @{id="L-000414"; lex="vosh"; root=$false; pos="предлог"; trans="ради, для, во имя"; etym="Предлог цели"; ex1="Talo vosh ruuna."; ex1t="Говорить ради общности."; ex2="Kalo vosh xha-ruun."; ex2t="Творить ради народа."; deriv="vosha"}
$entries += @{id="L-000415"; lex="dol"; root=$false; pos="союз"; trans="но, однако"; etym="Противительный союз"; ex1="Khar thel dol koss thel."; ex1t="Свет есть, но холод есть."; ex2="Xhare talo dol vene nel talo."; ex2t="Мыслитель говорит, но мудрец молчит."; deriv="dolae"}
$entries += @{id="L-000416"; lex="kan"; root=$false; pos="союз"; trans="когда, в то время как"; etym="Временной союз"; ex1="Kan ser thero, thal-khar thero."; ex1t="Когда луна восходит, наступает рассвет."; ex2="Kan ruun gatho, ruuno thero."; ex2t="Когда народ собирается, наступает собрание."; deriv="kansha"}
$entries += @{id="L-000417"; lex="vun"; root=$false; pos="союз"; trans="потому что, ибо"; etym="Причинный союз"; ex1="Xha-ruun maro ven vun ven thel vex."; ex1t="Народ чтит истину, ибо истина — сила."; ex2="More mor-thal solo vun mor thel xari."; ex2t="Моряк плавает, ибо вода — среда."; deriv="vunae"}
$entries += @{id="L-000418"; lex="shol"; root=$false; pos="предлог"; trans="под, ниже, внизу"; etym="Предлог нижнего положения"; ex1="Xare khal shol vash."; ex1t="Существо под камнем."; ex2="Mor shol kossi."; ex2t="Вода под ледником."; deriv="sholae"}
$entries += @{id="L-000419"; lex="kael"; root=$false; pos="предлог"; trans="над, выше, сверху"; etym="Предлог верхнего положения"; ex1="Khar-vex kael thali."; ex1t="Звезда над горизонтом."; ex2="Thal-ver kael kel-ver."; ex2t="Облако над горами."; deriv="kaelae"}
$entries += @{id="L-000420"; lex="rim"; root=$false; pos="предлог"; trans="между, среди"; etym="Предлог промежутка"; ex1="Ruun rim mor vel the."; ex1t="Народ между водой и землёй."; ex2="Xhare rim xha-ruunen."; ex2t="Мыслитель среди разумных."; deriv="rimae"}

$entries += @{id="L-000421"; lex="thok"; root=$false; pos="наречие"; trans="там, туда, в том месте"; etym="Указательное наречие места"; ex1="Thok thel mor-thal."; ex1t="Там океан."; ex2="Thok ruuni theri."; ex2t="Там поселение."; deriv="thokae"}
$entries += @{id="L-000422"; lex="thik"; root=$false; pos="наречие"; trans="здесь, тут, в этом месте"; etym="Указательное наречие места (близко)"; ex1="Thik thel xa-ruun."; ex1t="Здесь разумный народ."; ex2="Thik thel veni."; ex2t="Здесь архив знаний."; deriv="thikae"}
$entries += @{id="L-000423"; lex="losh"; root=$false; pos="наречие"; trans="сейчас, теперь"; etym="Наречие настоящего времени"; ex1="Losh xha-ruun talo."; ex1t="Сейчас народ говорит."; ex2="Losh thel thal-khar."; ex2t="Сейчас рассвет."; deriv="loshae"}
$entries += @{id="L-000424"; lex="vashun"; root=$false; pos="наречие"; trans="потом, затем, после"; etym="Наречие будущего/прошедшего времени"; ex1="Vashun ruun venun."; ex1t="Потом народ познает."; ex2="Vashun thel ser-thal."; ex2t="Потом будет ночь."; deriv="vashunae"}
$entries += @{id="L-000425"; lex="ethar"; root=$false; pos="числительное"; trans="один, первый"; etym="Базовое числительное"; ex1="Ethar xha-ruun."; ex1t="Один разумный народ."; ex2="Ethar thel khar-vex."; ex2t="Одна звезда."; deriv="etharae"}
$entries += @{id="L-000426"; lex="zethar"; root=$false; pos="числительное"; trans="два, второй"; etym="Базовое числительное"; ex1="Zethar xhare."; ex1t="Два мыслителя."; ex2="Zethar khar-vex-eth."; ex2t="Две звезды."; deriv="zetharae"}
$entries += @{id="L-000427"; lex="rethar"; root=$false; pos="числительное"; trans="три, третий"; etym="Базовое числительное"; ex1="Rethar ruune."; ex1t="Три общинника."; ex2="Rethar thel vokhri."; ex2t="Три храма."; deriv="retharae"}
$entries += @{id="L-000428"; lex="dolth"; root=$false; pos="наречие"; trans="только, лишь"; etym="Ограничительное наречие"; ex1="Dolth xha-ruun maro ven."; ex1t="Только разумный народ владеет истиной."; ex2="Dolth thel kharu."; ex2t="Лишь свет."; deriv="dolthae"}
$entries += @{id="L-000429"; lex="velth"; root=$false; pos="наречие"; trans="также, тоже"; etym="Наречие добавления"; ex1="Velth xhare veno."; ex1t="Также мыслитель познаёт."; ex2="Mor velth thel xari."; ex2t="Вода — также среда."; deriv="velthae"}
$entries += @{id="L-000430"; lex="nosh"; root=$false; pos="междометие"; trans="да, истинно, воистину"; etym="Утвердительное междометие"; ex1="Nosh! Thel vena."; ex1t="Да! Это истина."; ex2="Nosh, xha-ruun thel."; ex2t="Воистину, это народ."; deriv="noshsha"}

# ---- L-000431 to L-000450: More grammatical and derivational elements ----
$entries += @{id="L-000431"; lex="sha-ae"; root=$false; pos="суффикс"; trans="-ae: суффикс свойства, качественное прилагательное"; etym="Грамматический суффикс"; ex1="Vex-ae thel vexa."; ex1t="Сильный — сила."; ex2="Khar-ae thel khara."; ex2t="Светлый — свет."; deriv="sharae"}
$entries += @{id="L-000432"; lex="sha-el"; root=$false; pos="суффикс"; trans="-el: показатель прошедшего времени"; etym="Грамматический суффикс"; ex1="Xhare tal-el ven."; ex1t="Мыслитель сказал истину."; ex2="Ruun fen-el."; ex2t="Народ рос."; deriv="shael"}
$entries += @{id="L-000433"; lex="sha-un"; root=$false; pos="суффикс"; trans="-un: показатель будущего времени"; etym="Грамматический суффикс"; ex1="Xha-ruun thul-un."; ex1t="Народ построит."; ex2="Vashe kal-un."; ex2t="Строитель создаст."; deriv="shaun"}
$entries += @{id="L-000434"; lex="sha-il"; root=$false; pos="суффикс"; trans="-il: показатель пассивного залога"; etym="Грамматический суффикс"; ex1="Vashi kal-il."; ex1t="Здание создаётся."; ex2="Sha tal-il."; ex2t="Слово говорится."; deriv="shail"}
$entries += @{id="L-000435"; lex="sha-gath"; root=$false; pos="существительное"; trans="грамматика, строй языка"; etym="sha- (язык) + gath- (сбор): собрание языковых правил"; ex1="Sha-gath shari thero."; ex1t="Грамматика — словарь языка."; ex2="Xha-ruun maro sha-gath."; ex2t="Народ владеет грамматикой."; deriv="shagathae, shagathvene"}
$entries += @{id="L-000436"; lex="vun-sha"; root=$false; pos="существительное"; trans="причина, обоснование"; etym="vun- (причина) + sha- (слово)"; ex1="Vun-sha xhari thero."; ex1t="Причина рождается в разуме."; ex2="Vun-sha thel ven."; ex2t="Обоснование — истина."; deriv="vunshara, vunshare"}
$entries += @{id="L-000437"; lex="mer-ae"; root=$false; pos="прилагательное"; trans="сравнительный, -ее"; etym="Корень mer- + -aer (сравнительная степень)"; ex1="Mer-ae keli kel-thal."; ex1t="Выше зенита."; ex2="Mer-ae rhuri mor-thal."; ex2t="Океан больше простора?"; deriv="meraethal"}
$entries += @{id="L-000438"; lex="zha"; root=$false; pos="частица"; trans="пусть, да (пожелание)"; etym="Оптативная частица"; ex1="Zha ruun fenun!"; ex1t="Пусть народ растёт!"; ex2="Zha xha-ruun maro ven!"; ex2t="Да владеет народ истиной!"; deriv="zhasha"}
$entries += @{id="L-000439"; lex="kel-thal"; root=$false; pos="наречие"; trans="вверх, кверху"; etym="kel- (высота) + thal- (небо)"; ex1="Mero kel-thal!"; ex1t="Смотри вверх!"; ex2="Ren kel-thal thali."; ex2t="Идти вверх к горизонту."; deriv="kelthalae"}
$entries += @{id="L-000440"; lex="shol-mor"; root=$false; pos="наречие"; trans="вниз, книзу"; etym="shol- (под) + mor- (вода: нижняя стихия)"; ex1="Ren shol-mor."; ex1t="Идти вниз."; ex2="Lasho shol-mor vash-mor."; ex2t="Падать вниз на морское дно."; deriv="sholmorae"}

$entries += @{id="L-000441"; lex="theil"; root=$false; pos="существительное"; trans="век, эпоха, длительный период"; etym="Корень the- (земля) + -il (пассив), переносно"; ex1="Theil thel sera."; ex1t="Эпоха — цикл."; ex2="Xha-ruun maro theil."; ex2t="Народ помнит эпохи."; deriv="theilae, theilven"}
$entries += @{id="L-000442"; lex="mor-son"; root=$false; pos="существительное"; trans="ритм, пульс"; etym="mor- (вода) + son- (звук): звук воды"; ex1="Mor-son thel sera."; ex1t="Ритм — цикличность."; ex2="Xare hosho mor-son."; ex2t="Существо чувствует ритм."; deriv="morsonae, morsonxari"}
$entries += @{id="L-000443"; lex="tal-ki"; root=$false; pos="существительное"; trans="диалог, беседа (говорение-место)"; etym="tal- (говорение) + -ki (суффикс места по аналогии с -i)"; ex1="Tal-ki xhareno thero."; ex1t="Диалог — обмен мыслей."; ex2="Ruun thero tal-ki."; ex2t="Народ ведёт беседу."; deriv="talkirae, talkiven"}
$entries += @{id="L-000444"; lex="laen"; root=$false; pos="частица"; trans="уже, ещё"; etym="Временная частица аспекта"; ex1="Laen thel thal-khar."; ex1t="Уже рассвет."; ex2="Laen nel khar-thal."; ex2t="Ещё не рассвет."; deriv="laenel"}
$entries += @{id="L-000445"; lex="sha-tosh"; root=$false; pos="существительное"; trans="вопрос, запрос"; etym="sha- (слово) + tosh- (производное от вопросительной частицы)"; ex1="Sha-tosh khe?"; ex1t="Вопрос ли?"; ex2="Ruune talo sha-tosh."; ex2t="Общинник задаёт вопрос."; deriv="shatoshae"}
$entries += @{id="L-000446"; lex="nel-sha"; root=$false; pos="существительное"; trans="отрицание, запрет"; etym="nel (не) + sha (слово)"; ex1="Nel-sha ruuni theri."; ex1t="Запрет в поселении."; ex2="Nel-sha thel khal."; ex2t="Отрицание в языке."; deriv="nelsharae"}
$entries += @{id="L-000447"; lex="mer-ki"; root=$false; pos="существительное"; trans="точка зрения, перспектива"; etym="mer- (зрение) + -ki (суффикс места)"; ex1="Mer-ki xhari thero."; ex1t="Точка зрения в разуме."; ex2="Xhare maro mer-ki."; ex2t="Мыслитель имеет перспективу."; deriv="merkiae"}
$entries += @{id="L-000448"; lex="gath-thal"; root=$false; pos="существительное"; trans="созвездие (сбор-небо)"; etym="gath- (сбор) + thal- (небо)"; ex1="Gath-thal thali thero."; ex1t="Созвездие на горизонте."; ex2="Gath-thal thel khar-vex-eth."; ex2t="Созвездие — собрание звёзд."; deriv="gaththalae"}
$entries += @{id="L-000449"; lex="ven-thul"; root=$false; pos="существительное"; trans="теория, система знаний (истина-строение)"; etym="ven- (истина) + thul- (строение)"; ex1="Ven-thul xhari thero."; ex1t="Теория рождается в разуме."; ex2="Ruun maro ven-thul."; ex2t="Народ имеет теорию."; deriv="venthulae,venthulxha"}
$entries += @{id="L-000450"; lex="xha-gral"; root=$false; pos="существительное"; trans="понимание, усвоение (разум-поглощение)"; etym="xha- (разум) + gral- (поглощение)"; ex1="Xha-gral xhari thero."; ex1t="Понимание — в разуме."; ex2="Xha-ruun maro xha-gral."; ex2t="Народ обладает пониманием."; deriv="xhagralae"}

# Generate files
foreach ($e in $entries) {
    $rootFlag = if ($e.root) { "да" } else { "нет" }
    $content = @"
# $($e.id): $($e.lex)

**Корень:** $rootFlag
**Часть речи:** $($e.pos)
**Перевод:** $($e.trans)
**Статус:** active
**Создан:** $date

## Этимология

$($e.etym)

## Примеры

1. $($e.ex1) — $($e.ex1t)
2. $($e.ex2) — $($e.ex2t)

## Производные

$($e.deriv)
"@
    $filePath = Join-Path $basePath "$($e.id).md"
    Set-Content -Path $filePath -Value $content -Encoding UTF8
    Write-Output "Created $($e.id)"
}
