$basePath = "C:\Cloude\registry\lexemes"
$date = "2026-07-16"

$entries = @()

# ========== Section 2: L-000101 to L-000300 — Compound words (nature, geography, skies) ==========

$entries += @{id="L-000101"; lex="mor-thal"; pos="существительное"; trans="океан (вода-небо)"; etym="mor- (вода) + thal- (небо): вода под небом"; ex1="Mor-thal thel rhuri."; ex1t="Океан — великий простор."; ex2="Mor-thal thel xaro."; ex2t="Океан полон жизни."; deriv="morthalae, morthalxare"}
$entries += @{id="L-000102"; lex="khar-vex"; pos="существительное"; trans="звезда (свет-сила)"; etym="khar- (свет) + vex- (сила): светящаяся сила"; ex1="Khar-vex thali thero."; ex1t="Звезда восходит к горизонту."; ex2="Khar-vex thel kharu."; ex2t="Звезда излучает свет."; deriv="kharvexae, kharvexxare"}
$entries += @{id="L-000103"; lex="kel-ver"; pos="существительное"; trans="горный хребет (высота-гора)"; etym="kel- (высота) + ver- (гора)"; ex1="Kel-ver thali thero."; ex1t="Хребет поднимается к небу."; ex2="Kel-ver thel kossi."; ex2t="Хребет держит ледники."; deriv="kelverae, kelvervash"}
$entries += @{id="L-000104"; lex="the-mor"; pos="существительное"; trans="болото, трясина (земля-вода)"; etym="the- (земля) + mor- (вода)"; ex1="The-mor thel xari."; ex1t="Болото — особая среда."; ex2="The-mor zhalo thero."; ex2t="Болото дышит туманом."; deriv="themorae, themorxare"}
$entries += @{id="L-000105"; lex="thal-zhal"; pos="существительное"; trans="атмосфера (небо-воздух)"; etym="thal- (небо) + zhal- (воздух)"; ex1="Thal-zhal thel zhali."; ex1t="Атмосфера — воздушный слой."; ex2="Thal-zhal thel xaro."; ex2t="Атмосфера защищает жизнь."; deriv="thalzhalae, thalzhalven"}
$entries += @{id="L-000106"; lex="vash-kel"; pos="существительное"; trans="скалистая вершина, пик (камень-высота)"; etym="vash- (камень) + kel- (высота)"; ex1="Vash-kel thali thero."; ex1t="Пик пронзает горизонт."; ex2="Vash-kel thel veri."; ex2t="Вершина стоит на скале."; deriv="vashkelae, vashkelxare"}
$entries += @{id="L-000107"; lex="koss-mor"; pos="существительное"; trans="ледник (лёд-вода)"; etym="koss- (лёд) + mor- (вода)"; ex1="Koss-mor kel-ver theri."; ex1t="Ледник лежит в горах."; ex2="Koss-mor moro thero."; ex2t="Ледник рождает ручьи."; deriv="kossmorae, kossmorvash"}
$entries += @{id="L-000108"; lex="xha-ruun"; pos="существительное"; trans="разумный народ, самоназвание (разум-народ)"; etym="xha- (разум) + ruun- (народ)"; ex1="Xha-ruun thali thero."; ex1t="Разумный народ смотрит в небо."; ex2="Xha-ruun veni vexo."; ex2t="Народ чтит знание."; deriv="xharuunae, xharuunsha"}
$entries += @{id="L-000109"; lex="khar-thal"; pos="существительное"; trans="небосвод, твердь небесная (свет-небо)"; etym="khar- (свет) + thal- (небо)"; ex1="Khar-thal thali thero."; ex1t="Небосвод сияет вдали."; ex2="Khar-thal thel xhara."; ex2t="Свет небес питает разум."; deriv="kharthalae, kharthalvex"}
$entries += @{id="L-000110"; lex="the-vash"; pos="существительное"; trans="скальное основание, фундамент земли (земля-камень)"; etym="the- (земля) + vash- (камень)"; ex1="The-vash ruuni theri."; ex1t="Скала держит поселение."; ex2="The-vash thel theri."; ex2t="Основание — сама земля."; deriv="thevashae, thevashxari"}
$entries += @{id="L-000111"; lex="mor-ver"; pos="существительное"; trans="водопад (вода-гора)"; etym="mor- (вода) + ver- (гора)"; ex1="Mor-ver thel vexo."; ex1t="Водопад несёт силу."; ex2="Mor-ver thel kharu."; ex2t="Водопад сверкает на свету."; deriv="morverae, morverzhal"}
$entries += @{id="L-000112"; lex="thal-khar"; pos="существительное"; trans="рассвет (небо-свет)"; etym="thal- (небо) + khar- (свет): рождение света в небе"; ex1="Thal-khar thel kharu."; ex1t="Рассвет несёт свет."; ex2="Thal-khar ruuni vexo."; ex2t="Рассвет пробуждает народ."; deriv="thalkharae, thalkharxare"}
$entries += @{id="L-000113"; lex="koss-thal"; pos="существительное"; trans="полярное сияние (лёд-небо)"; etym="koss- (лёд) + thal- (небо)"; ex1="Koss-thal thali thero."; ex1t="Сияние танцует в небе."; ex2="Koss-thal thel kharu."; ex2t="Сияние — свет холода."; deriv="kossthalae, kossthalvex"}
$entries += @{id="L-000114"; lex="zhal-mor"; pos="существительное"; trans="туман (воздух-вода)"; etym="zhal- (воздух) + mor- (вода)"; ex1="Zhal-mor theri thero."; ex1t="Туман стелется по земле."; ex2="Zhal-mor thel xari."; ex2t="Туман — влажная среда."; deriv="zhalmorae, zhalmorxare"}
$entries += @{id="L-000115"; lex="ser-thal"; pos="существительное"; trans="ночное небо (луна-небо)"; etym="ser- (луна) + thal- (небо)"; ex1="Ser-thal thel sera."; ex1t="Ночное небо циклично."; ex2="Ser-thal thali thero."; ex2t="Ночь открывает звёзды."; deriv="serthalae, serthalxhare"}
$entries += @{id="L-000116"; lex="kel-rhu"; pos="существительное"; trans="величайшая вершина, абсолютная высота (высота-великий)"; etym="kel- (высота) + rhu- (великий)"; ex1="Kel-rhu thali thero."; ex1t="Великая вершина в небе."; ex2="Kel-rhu thel vera."; ex2t="Вершина — символ несокрушимости."; deriv="kelrhurae, kelrhuvex"}
$entries += @{id="L-000117"; lex="the-rass"; pos="существительное"; trans="равнина (земля-пространство)"; etym="the- (земля) + rass- (пространство)"; ex1="The-rass thel rhuri."; ex1t="Равнина — земной простор."; ex2="The-rass thali thero."; ex2t="Равнина уходит к горизонту."; deriv="therassae, therassxare"}
$entries += @{id="L-000118"; lex="mor-koss"; pos="существительное"; trans="айсберг (вода-лёд)"; etym="mor- (вода) + koss- (лёд)"; ex1="Mor-koss mor-thal thero."; ex1t="Айсберг плывёт в океане."; ex2="Mor-koss thel kossi."; ex2t="Айсберг — плавучий лёд."; deriv="morkossae, morkossvash"}
$entries += @{id="L-000119"; lex="vash-mor"; pos="существительное"; trans="морское дно (камень-вода)"; etym="vash- (камень) + mor- (вода)"; ex1="Vash-mor thel xari."; ex1t="Дно — глубинная среда."; ex2="Vash-mor mori theri."; ex2t="Дно хранит воды."; deriv="vashmorae, vashmorxare"}
$entries += @{id="L-000120"; lex="thal-rass"; pos="существительное"; trans="космос, открытое пространство (небо-пространство)"; etym="thal- (небо) + rass- (пространство)"; ex1="Thal-rass thel rhuri."; ex1t="Космос — величайший простор."; ex2="Thal-rass khar-vex thero."; ex2t="В космосе рождаются звёзды."; deriv="thalrassae, thalrassven"}
$entries += @{id="L-000121"; lex="khar-mor"; pos="существительное"; trans="отражение, блик на воде (свет-вода)"; etym="khar- (свет) + mor- (вода)"; ex1="Khar-mor mori thero."; ex1t="Блик танцует на воде."; ex2="Khar-mor thel kharu."; ex2t="Отражение — вторичный свет."; deriv="kharmorae, kharmorxhari"}
$entries += @{id="L-000122"; lex="vash-thal"; pos="существительное"; trans="небесный свод, твердь (камень-небо)"; etym="vash- (камень) + thal- (небо): небо как структура"; ex1="Vash-thal thel khar-vex."; ex1t="Небесный свод держит звёзды."; ex2="Vash-thal thal-rass theri."; ex2t="Твердь отделяет небо от космоса."; deriv="vashthalae, vashthalven"}
$entries += @{id="L-000123"; lex="zhal-kel"; pos="существительное"; trans="ветер на высоте (воздух-высота)"; etym="zhal- (воздух) + kel- (высота)"; ex1="Zhal-kel keli thero."; ex1t="Ветер дует на вершине."; ex2="Zhal-kel thel vexo."; ex2t="Высотный ветер несёт силу."; deriv="zhalkelae, zhalkelzhalo"}
$entries += @{id="L-000124"; lex="mor-sha"; pos="существительное"; trans="песня воды, журчание (вода-слово)"; etym="mor- (вода) + sha- (слово)"; ex1="Mor-sha moro thero."; ex1t="Вода поёт в ручье."; ex2="Mor-sha thel shara."; ex2t="Журчание — язык воды."; deriv="morsharae, morshavex"}
$entries += @{id="L-000125"; lex="khar-ven"; pos="существительное"; trans="озарение, прозрение (свет-истина)"; etym="khar- (свет) + ven- (истина)"; ex1="Khar-ven xhari thero."; ex1t="Озарение вспыхивает в разуме."; ex2="Khar-ven thel sharu."; ex2t="Прозрение рождает слово."; deriv="kharvenae, kharvenxhare"}
$entries += @{id="L-000126"; lex="the-zhal"; pos="существительное"; trans="испарение, пар (земля-воздух)"; etym="the- (земля) + zhal- (воздух)"; ex1="The-zhal theri thero."; ex1t="Пар поднимается от земли."; ex2="The-zhal zhal-mor thero."; ex2t="Испарение становится туманом."; deriv="thezhalae, thezhalmor"}
$entries += @{id="L-000127"; lex="xha-ser"; pos="существительное"; trans="цикл мысли, медитация (мысль-цикл)"; etym="xha- (разум) + ser- (цикл/луна)"; ex1="Xha-ser xhari thero."; ex1t="Медитация очищает разум."; ex2="Xha-ser thel sera."; ex2t="Цикл мысли — как фазы луны."; deriv="xhaserae, xhaserveno"}
$entries += @{id="L-000128"; lex="ruun-thal"; pos="существительное"; trans="небесная община, утопия (народ-небо)"; etym="ruun- (народ) + thal- (небо)"; ex1="Ruun-thal thel xha-ruun."; ex1t="Утопия — идеальный народ."; ex2="Ruun-thal thel vokhra."; ex2t="Небесная община живёт в гармонии."; deriv="ruunthalae, ruunthalvokh"}
$entries += @{id="L-000129"; lex="vash-ven"; pos="существительное"; trans="древняя истина, высеченная в камне (камень-истина)"; etym="vash- (камень) + ven- (истина)"; ex1="Vash-ven thel vena."; ex1t="Истина в камне вечна."; ex2="Vash-ven ruuni theri."; ex2t="Каменная истина хранит народ."; deriv="vashvenae, vashvensh a"}
$entries += @{id="L-000130"; lex="khar-koss"; pos="существительное"; trans="солнечный блик на льду (свет-лёд)"; etym="khar- (свет) + koss- (лёд)"; ex1="Khar-koss kossi thero."; ex1t="Свет играет на леднике."; ex2="Khar-koss thel vexa."; ex2t="Лёд отражает мощь света."; deriv="kharkossae, kharkossxare"}

$entries += @{id="L-000131"; lex="mor-sha"; pos="существительное"; trans="песня воды, журчание"; etym="mor- (вода) + sha- (слово/язык)"; ex1="Mor-sha moro thero."; ex1t="Вода поёт в ручье."; ex2="Mor-sha thel sharu."; ex2t="Журчание — высказывание воды."; deriv="morsharae, morshavex"}
$entries += @{id="L-000132"; lex="kel-zhal"; pos="существительное"; trans="горный воздух (высота-воздух)"; etym="kel- (высота) + zhal- (воздух)"; ex1="Kel-zhal keli thero."; ex1t="Горный воздух чист на вершине."; ex2="Kel-zhal thel xaro."; ex2t="Высокий воздух даёт жизнь."; deriv="kelzhalae, kelzhalxare"}
$entries += @{id="L-000133"; lex="the-ver"; pos="существительное"; trans="предгорье, подножие (земля-гора)"; etym="the- (земля) + ver- (гора)"; ex1="The-ver veri theri."; ex1t="Предгорье у подножия скалы."; ex2="The-ver thel mor-ver."; ex2t="У подножия горы — водопад."; deriv="theverae, theverruuni"}
$entries += @{id="L-000134"; lex="vex-ser"; pos="существительное"; trans="приливная сила, гравитация (сила-луна)"; etym="vex- (сила) + ser- (луна)"; ex1="Vex-ser mor-thal vexo."; ex1t="Прилив движет океан."; ex2="Vex-ser thel sero."; ex2t="Сила луны — во вращении."; deriv="vexserae, vexserven"}
$entries += @{id="L-000135"; lex="vash-zhal"; pos="существительное"; trans="пемза, пористый камень (камень-воздух)"; etym="vash- (камень) + zhal- (воздух)"; ex1="Vash-zhal theri thero."; ex1t="Пемза плавает в воде."; ex2="Vash-zhal thel zhala."; ex2t="Камень дышит воздухом."; deriv="vashzhalae, vashzhalver"}
$entries += @{id="L-000136"; lex="xha-mor"; pos="существительное"; trans="глубинная мысль, подсознание (разум-вода)"; etym="xha- (разум) + mor- (вода)"; ex1="Xha-mor xhari thero."; ex1t="Глубинная мысль течёт в подсознании."; ex2="Xha-mor thel xharu."; ex2t="Из глубин рождаются идеи."; deriv="xhamorae, xhamorven"}
$entries += @{id="L-000137"; lex="ruun-kel"; pos="существительное"; trans="высший совет народа (народ-высота)"; etym="ruun- (народ) + kel- (высота)"; ex1="Ruun-kel ruuni thero."; ex1t="Совет правит поселением."; ex2="Ruun-kel thel vokha."; ex2t="Высший совет — опора порядка."; deriv="ruunkelae, ruunkelvokhre"}
$entries += @{id="L-000138"; lex="mor-vex"; pos="существительное"; trans="гидроэнергия, сила воды (вода-сила)"; etym="mor- (вода) + vex- (сила)"; ex1="Mor-vex moro thero."; ex1t="Сила воды — в течении."; ex2="Mor-vex ruuni vexo."; ex2t="Вода питает народ."; deriv="morvexae, morvexvashi"}
$entries += @{id="L-000139"; lex="thal-ver"; pos="существительное"; trans="облако, небесная гора (небо-гора)"; etym="thal- (небо) + ver- (гора)"; ex1="Thal-ver thali thero."; ex1t="Облако плывёт к горизонту."; ex2="Thal-ver zhal-mor theri."; ex2t="Облако состоит из тумана."; deriv="thalverae, thalverzhal"}
$entries += @{id="L-000140"; lex="the-koss"; pos="существительное"; trans="вечная мерзлота (земля-лёд)"; etym="the- (земля) + koss- (лёд)"; ex1="The-koss theri thero."; ex1t="Мерзлота сковала землю."; ex2="The-koss thel kossi."; ex2t="Мёрзлая земля — ледник."; deriv="thekossae, thekossxari"}
$entries += @{id="L-000141"; lex="khar-zhal"; pos="существительное"; trans="мираж, игра света в воздухе (свет-воздух)"; etym="khar- (свет) + zhal- (воздух)"; ex1="Khar-zhal thali thero."; ex1t="Мираж дрожит у горизонта."; ex2="Khar-zhal thel the-rass."; ex2t="Мираж — свет над равниной."; deriv="kharzhalae, kharzhalxari"}
$entries += @{id="L-000142"; lex="ven-xha"; pos="существительное"; trans="философия, мудрость (истина-разум)"; etym="ven- (истина) + xha- (разум)"; ex1="Ven-xha ruuni thero."; ex1t="Философия ведёт народ."; ex2="Ven-xha thel sharu."; ex2t="Мудрость рождает слово."; deriv="venxharae, venxhaxhare"}
$entries += @{id="L-000143"; lex="sha-ruun"; pos="существительное"; trans="народный язык, наречие (слово-народ)"; etym="sha- (язык) + ruun- (народ)"; ex1="Sha-ruun ruuni theri."; ex1t="Народный язык объединяет."; ex2="Sha-ruun thel shara."; ex2t="Наречие — душа народа."; deriv="sharuunae, sharuunven"}
$entries += @{id="L-000144"; lex="vokh-rass"; pos="существительное"; trans="космический порядок, гармония сфер (порядок-пространство)"; etym="vokh- (порядок) + rass- (пространство)"; ex1="Vokh-rass thal-rass thero."; ex1t="Порядок царит в космосе."; ex2="Vokh-rass thel vokhra."; ex2t="Гармония сфер — высший порядок."; deriv="vokhrassae, vokhrassven"}
$entries += @{id="L-000145"; lex="xha-vex"; pos="существительное"; trans="сила мысли, воля (разум-сила)"; etym="xha- (разум) + vex- (сила)"; ex1="Xha-vex xhare thero."; ex1t="Воля движет мыслителем."; ex2="Xha-vex thel vexo."; ex2t="Сила мысли — в действии."; deriv="xhavexae, xhavexxhare"}
$entries += @{id="L-000146"; lex="mor-kel"; pos="существительное"; trans="морская высота, волна (вода-высота)"; etym="mor- (вода) + kel- (высота)"; ex1="Mor-kel mor-thal thero."; ex1t="Волна поднимается в океане."; ex2="Mor-kel thel vexo."; ex2t="Волна несёт энергию."; deriv="morkelae, morkelvashi"}
$entries += @{id="L-000147"; lex="the-vex"; pos="существительное"; trans="геотермальная энергия (земля-сила)"; etym="the- (земля) + vex- (сила)"; ex1="The-vex theri thero."; ex1t="Земная сила глубока."; ex2="The-vex thel vexi."; ex2t="Геотермия — источник силы."; deriv="thevexae, thevexvashi"}
$entries += @{id="L-000148"; lex="ven-sha"; pos="существительное"; trans="правда, истинное слово (истина-слово)"; etym="ven- (истина) + sha- (слово)"; ex1="Ven-sha ruuni thero."; ex1t="Правда ведёт народ."; ex2="Ven-sha thel vena."; ex2t="Истинное слово — это истина."; deriv="vensharae, venshaxhare"}
$entries += @{id="L-000149"; lex="koss-ver"; pos="существительное"; trans="заснеженная гора (лёд-гора)"; etym="koss- (лёд) + ver- (гора)"; ex1="Koss-ver keli thero."; ex1t="Снежная гора сверкает вершиной."; ex2="Koss-ver thel kossi."; ex2t="Гора покрыта ледником."; deriv="kossverae, kossverkossi"}
$entries += @{id="L-000150"; lex="zhal-vex"; pos="существительное"; trans="ветровая энергия (воздух-сила)"; etym="zhal- (воздух) + vex- (сила)"; ex1="Zhal-vex thali thero."; ex1t="Ветер несёт силу."; ex2="Zhal-vex thel vexi."; ex2t="Ветровая энергия питает."; deriv="zhalvexae, zhalvexvashi"}
$entries += @{id="L-000151"; lex="xha-thal"; pos="существительное"; trans="мечта, воображение (разум-небо)"; etym="xha- (разум) + thal- (небо)"; ex1="Xha-thal xhari thero."; ex1t="Мечта рождается в разуме."; ex2="Xha-thal thel rhuri."; ex2t="Воображение — простор мысли."; deriv="xhathalae, xhathalxhare"}
$entries += @{id="L-000152"; lex="ruun-mor"; pos="существительное"; trans="народ, живущий у океана (народ-вода)"; etym="ruun- (народ) + mor- (вода)"; ex1="Ruun-mor mor-thal thero."; ex1t="Прибрежный народ живёт океаном."; ex2="Ruun-mor mor-vex veno."; ex2t="Морской народ знает силу воды."; deriv="ruunmorae, ruunmorsha"}
$entries += @{id="L-000153"; lex="vash-koss"; pos="существительное"; trans="иней, изморозь на камне (камень-лёд)"; etym="vash- (камень) + koss- (лёд)"; ex1="Vash-koss veri thero."; ex1t="Иней покрывает скалу."; ex2="Vash-koss thel kossa."; ex2t="Камень дышит холодом."; deriv="vashkossae, vashkossxari"}
$entries += @{id="L-000154"; lex="khar-ruun"; pos="существительное"; trans="избранный народ, светоч народа (свет-народ)"; etym="khar- (свет) + ruun- (народ)"; ex1="Khar-ruun thali thero."; ex1t="Светоч ведёт народ в будущее."; ex2="Khar-ruun thel xha-ruun."; ex2t="Избранные — разум народа."; deriv="kharmorae, kharmorxari"}
$entries += @{id="L-000155"; lex="the-ven"; pos="существительное"; trans="геология, знание о земле (земля-знание)"; etym="the- (земля) + ven- (знание)"; ex1="The-ven theri thero."; ex1t="Геология изучает землю."; ex2="The-ven thel vena."; ex2t="Знание о земле — истина."; deriv="thevenae, thevenvene"}
$entries += @{id="L-000156"; lex="mor-xha"; pos="существительное"; trans="интуиция, чутьё (вода-разум)"; etym="mor- (вода) + xha- (разум)"; ex1="Mor-xha xhari thero."; ex1t="Интуиция течёт в разуме."; ex2="Mor-xha thel veno."; ex2t="Чутьё — видение истины."; deriv="morxharae, morxhaxhare"}
$entries += @{id="L-000157"; lex="thal-vex"; pos="существительное"; trans="метеорит, небесная сила (небо-сила)"; etym="thal- (небо) + vex- (сила)"; ex1="Thal-vex thel khar-vex."; ex1t="Метеорит — падающая звезда."; ex2="Thal-vex theri thero."; ex2t="Небесная сила ударяет в землю."; deriv="thalvexae, thalvexvash"}
$entries += @{id="L-000158"; lex="sha-ven"; pos="существительное"; trans="аксиома, доказанное знание (слово-истина)"; etym="sha- (слово) + ven- (истина)"; ex1="Sha-ven thel vena."; ex1t="Аксиома — истинное слово."; ex2="Sha-ven xhari thero."; ex2t="Доказанное знание утверждается разумом."; deriv="shavenae, shavenxhare"}
$entries += @{id="L-000159"; lex="koss-zhal"; pos="существительное"; trans="морозный воздух (лёд-воздух)"; etym="koss- (лёд) + zhal- (воздух)"; ex1="Koss-zhal kossi thero."; ex1t="Морозный воздух над ледником."; ex2="Koss-zhal thel kossa."; ex2t="Холод пронизывает воздух."; deriv="kosszhalae, kosszhalxare"}
$entries += @{id="L-000160"; lex="the-ser"; pos="существительное"; trans="время года, сезон (земля-цикл)"; etym="the- (земля) + ser- (цикл)"; ex1="The-ser theri thero."; ex1t="Сезон меняет землю."; ex2="The-ser thel xaro."; ex2t="Времена года влияют на жизнь."; deriv="theserae, theserven"}

$entries += @{id="L-000161"; lex="ven-thal"; pos="существительное"; trans="астрономия, знание о небе (знание-небо)"; etym="ven- (знание) + thal- (небо)"; ex1="Ven-thal thal-rass thero."; ex1t="Астрономия изучает космос."; ex2="Ven-thal khar-vex veno."; ex2t="Наука о небе познаёт звёзды."; deriv="venthali, venhalvene"}
$entries += @{id="L-000162"; lex="xha-koss"; pos="существительное"; trans="холодный расчёт, логика (разум-холод)"; etym="xha- (разум) + koss- (холод)"; ex1="Xha-koss xhari thero."; ex1t="Холодный расчёт — в разуме."; ex2="Xha-koss thel veno."; ex2t="Логика ведёт к истине."; deriv="xhakossae, xhakossxhare"}
$entries += @{id="L-000163"; lex="ruun-zhal"; pos="существительное"; trans="молва, народная молва (народ-воздух)"; etym="ruun- (народ) + zhal- (воздух)"; ex1="Ruun-zhal ruuni thero."; ex1t="Молва летит по народу."; ex2="Ruun-zhal thel sharu."; ex2t="Молва — слово без истины."; deriv="ruunzhalae, ruunzhalven"}
$entries += @{id="L-000164"; lex="vash-rass"; pos="существительное"; trans="каменная пустошь, плато (камень-пространство)"; etym="vash- (камень) + rass- (пространство)"; ex1="Vash-rass thel the-rass."; ex1t="Плато — каменная равнина."; ex2="Vash-rass thali thero."; ex2t="Пустошь уходит горизонту."; deriv="vashrassae, vashrassxari"}
$entries += @{id="L-000165"; lex="sha-thal"; pos="существительное"; trans="поэзия, небесное слово (слово-небо)"; etym="sha- (слово) + thal- (небо)"; ex1="Sha-thal xhari thero."; ex1t="Поэзия — небо в разуме."; ex2="Sha-thal thel sharu."; ex2t="Небесное слово — высшая речь."; deriv="shathalae, shathalshare"}
$entries += @{id="L-000166"; lex="vex-ruun"; pos="существительное"; trans="власть, сила народа (сила-народ)"; etym="vex- (сила) + ruun- (народ)"; ex1="Vex-ruun ruuni theri."; ex1t="Власть в руках народа."; ex2="Vex-ruun thel vexa."; ex2t="Сила народа — в единстве."; deriv="vexruunae, vexruunvokhre"}
$entries += @{id="L-000167"; lex="khar-ver"; pos="существительное"; trans="солнечный удар по горе, закат на горе (свет-гора)"; etym="khar- (свет) + ver- (гора)"; ex1="Khar-ver keli thero."; ex1t="Закат окрашивает гору."; ex2="Khar-ver thel kharu."; ex2t="Гора встречает последний луч."; deriv="kharverae, kharverxari"}
$entries += @{id="L-000168"; lex="mor-the"; pos="существительное"; trans="подземные воды, грунтовые воды (вода-земля)"; etym="mor- (вода) + the- (земля)"; ex1="Mor-the theri thero."; ex1t="Грунтовые воды текут под землёй."; ex2="Mor-the thel xari."; ex2t="Подземные воды питают жизнь."; deriv="mortherae, mortheven"}
$entries += @{id="L-000169"; lex="koss-vash"; pos="существительное"; trans="вечная мерзлота, ледяная порода (лёд-камень)"; etym="koss- (лёд) + vash- (камень)"; ex1="Koss-vash theri thero."; ex1t="Ледяная порода скована холодом."; ex2="Koss-vash thel kossi."; ex2t="Мерзлота — каменный лёд."; deriv="kossvashae, kossvashxari"}
$entries += @{id="L-000170"; lex="xha-ven"; pos="существительное"; trans="интеллект, познающий разум (разум-истина)"; etym="xha- (разум) + ven- (истина)"; ex1="Xha-ven thel xharo."; ex1t="Познающий разум мыслит."; ex2="Xha-ven thali thero."; ex2t="Интеллект ищет истину."; deriv="xhavenae, xhavenxhare"}

$entries += @{id="L-000171"; lex="sha-mor"; pos="существительное"; trans="легенда, сказание как река (слово-вода)"; etym="sha- (слово) + mor- (вода)"; ex1="Sha-mor ruuni thero."; ex1t="Легенды текут через поколения."; ex2="Sha-mor thel xharu."; ex2t="Сказание несёт идею."; deriv="shamorae, shamorxhare"}
$entries += @{id="L-000172"; lex="kel-thal"; pos="существительное"; trans="зенит, высшая точка неба (высота-небо)"; etym="kel- (высота) + thal- (небо)"; ex1="Kel-thal thali thero."; ex1t="Зенит — середина неба."; ex2="Kel-thal thel khar-vex."; ex2t="В зените — звезда."; deriv="kelthalae, kelthalven"}
$entries += @{id="L-000173"; lex="vash-ver"; pos="существительное"; trans="уступ, скальный карниз (камень-гора)"; etym="vash- (камень) + ver- (гора)"; ex1="Vash-ver veri thero."; ex1t="Уступ выступает из скалы."; ex2="Vash-ver thel vashi."; ex2t="Карниз — часть строения горы."; deriv="vashverae, vashverxari"}
$entries += @{id="L-000174"; lex="zhal-thal"; pos="существительное"; trans="небесные ветры, пассаты (воздух-небо)"; etym="zhal- (воздух) + thal- (небо)"; ex1="Zhal-thal thali thero."; ex1t="Пассаты дуют у горизонта."; ex2="Zhal-thal thel zhalo."; ex2t="Ветры — дыхание неба."; deriv="zhalthalae, zhalthalxare"}
$entries += @{id="L-000175"; lex="vex-mor"; pos="существительное"; trans="цунами, удар воды (сила-вода)"; etym="vex- (сила) + mor- (вода)"; ex1="Vex-mor mor-thal thero."; ex1t="Цунами рождается в океане."; ex2="Vex-mor thel vexa."; ex2t="Удар воды — великая мощь."; deriv="vexmorae, vexmorvash"}
$entries += @{id="L-000176"; lex="ruun-ven"; pos="существительное"; trans="народная мудрость, традиция (народ-истина)"; etym="ruun- (народ) + ven- (истина)"; ex1="Ruun-ven ruuni theri."; ex1t="Традиция хранит народ."; ex2="Ruun-ven thel vena."; ex2t="Народная мудрость — истина."; deriv="ruunvenae, ruunvenvene"}
$entries += @{id="L-000177"; lex="sha-khar"; pos="существительное"; trans="откровение, слово света (слово-свет)"; etym="sha- (слово) + khar- (свет)"; ex1="Sha-khar xhari thero."; ex1t="Откровение озаряет разум."; ex2="Sha-khar thel sharu."; ex2t="Слово света — истина."; deriv="shakharae, shakharxhare"}
$entries += @{id="L-000178"; lex="mor-zhal"; pos="существительное"; trans="пар, влажный воздух (вода-воздух)"; etym="mor- (вода) + zhal- (воздух)"; ex1="Mor-zhal theri thero."; ex1t="Пар поднимается от земли."; ex2="Mor-zhal thel zhal-mor."; ex2t="Влажный воздух — невидимый туман."; deriv="morzhalae, morzhalxari"}
$entries += @{id="L-000179"; lex="koss-kel"; pos="существительное"; trans="снежная вершина (лёд-высота)"; etym="koss- (лёд) + kel- (высота)"; ex1="Koss-kel thali thero."; ex1t="Снежная шапка на вершине."; ex2="Koss-kel thel kossi."; ex2t="Ледник венчает высоту."; deriv="kosskelae, kosskelver"}
$entries += @{id="L-000180"; lex="ven-kel"; pos="существительное"; trans="высшее знание, эзотерика (истина-высота)"; etym="ven- (истина) + kel- (высота)"; ex1="Ven-kel thali thero."; ex1t="Высшее знание за горизонтом."; ex2="Ven-kel thel veno."; ex2t="Сокровенное знание ждёт познания."; deriv="venkelae, venkelvene"}

$entries += @{id="L-000181"; lex="xha-rass"; pos="существительное"; trans="воображение, ментальное пространство (разум-пространство)"; etym="xha- (разум) + rass- (пространство)"; ex1="Xha-rass xhari thero."; ex1t="Разум создаёт пространства."; ex2="Xha-rass thel thal-rass."; ex2t="Мысль путешествует в космосе."; deriv="xharassae, xharassrasser"}
$entries += @{id="L-000182"; lex="ruun-vex"; pos="существительное"; trans="коллективная сила, мощь народа (народ-сила)"; etym="ruun- (народ) + vex- (сила)"; ex1="Ruun-vex ruuni thero."; ex1t="Коллективная сила движет народом."; ex2="Ruun-vex thel vexa."; ex2t="Сила народа — в единстве."; deriv="ruunvexae, ruunvexvokhre"}
$entries += @{id="L-000183"; lex="vash-xha"; pos="существительное"; trans="память, запечатлённая в камне (камень-разум)"; etym="vash- (камень) + xha- (разум)"; ex1="Vash-xha ruuni theri."; ex1t="Память камня хранит историю."; ex2="Vash-xha thel veni."; ex2t="В камне — знание веков."; deriv="vashxharae, vashxhaxhare"}
$entries += @{id="L-000184"; lex="the-xha"; pos="существительное"; trans="экология, наука о доме (земля-разум)"; etym="the- (земля) + xha- (разум)"; ex1="The-xha theri thero."; ex1t="Экология изучает землю."; ex2="The-xha thel xhara."; ex2t="Наука о земле — разумность."; deriv="thexharae, thexhaxhare"}
$entries += @{id="L-000185"; lex="sha-rass"; pos="существительное"; trans="эпос, пространство сказаний (слово-пространство)"; etym="sha- (слово) + rass- (пространство)"; ex1="Sha-rass ruuni thero."; ex1t="Эпос живёт в народе."; ex2="Sha-rass thel sharu."; ex2t="Пространство слова — безгранично."; deriv="sharassae, sharassxhare"}
$entries += @{id="L-000186"; lex="mor-ser"; pos="существительное"; trans="прилив, отлив (вода-цикл)"; etym="mor- (вода) + ser- (цикл)"; ex1="Mor-ser mor-thal thero."; ex1t="Прилив движет океан."; ex2="Mor-ser thel sera."; ex2t="Цикл воды — вечен."; deriv="morserae, morserven"}
$entries += @{id="L-000187"; lex="kel-mor"; pos="существительное"; trans="водопад с высоты, каскад (высота-вода)"; etym="kel- (высота) + mor- (вода)"; ex1="Kel-mor veri thero."; ex1t="Каскад низвергается со скалы."; ex2="Kel-mor thel vexo."; ex2t="Высота воды — сила."; deriv="kelmorae, kelmorxari"}
$entries += @{id="L-000188"; lex="khar-ser"; pos="существительное"; trans="фазы света, суточный цикл (свет-цикл)"; etym="khar- (свет) + ser- (цикл)"; ex1="Khar-ser thal-khar thero."; ex1t="Цикл света рождает рассвет."; ex2="Khar-ser thel sera."; ex2t="Солнце и луна — свет цикла."; deriv="kharserae, kharserven"}
$entries += @{id="L-000189"; lex="zhal-ruun"; pos="существительное"; trans="кочевой народ (воздух-народ)"; etym="zhal- (воздух) + ruun- (народ)"; ex1="Zhal-ruun thali thero."; ex1t="Кочевники идут к горизонту."; ex2="Zhal-ruun thel xari."; ex2t="Вольный народ живёт в пути."; deriv="zhalruunae, zhalruunsha"}
$entries += @{id="L-000190"; lex="vex-thal"; pos="существительное"; trans="молния, небесный разряд (сила-небо)"; etym="vex- (сила) + thal- (небо)"; ex1="Vex-thal thali thero."; ex1t="Молния бьёт с неба."; ex2="Vex-thal thel vexa."; ex2t="Небесный разряд — чистая сила."; deriv="vexthalae, vexthalxari"}

$entries += @{id="L-000191"; lex="the-ruun"; pos="существительное"; trans="оседлый народ, коренные жители (земля-народ)"; etym="the- (земля) + ruun- (народ)"; ex1="The-ruun theri thero."; ex1t="Оседлый народ живёт на земле."; ex2="The-ruun thel ruuni."; ex2t="Коренные жители основали поселение."; deriv="theruunae, theruunsha"}
$entries += @{id="L-000192"; lex="mor-ruun"; pos="существительное"; trans="морской народ (вода-народ)"; etym="mor- (вода) + ruun- (народ)"; ex1="Mor-ruun mor-thal thero."; ex1t="Морской народ плавает в океане."; ex2="Mor-ruun mor-vex veno."; ex2t="Морской народ знает силу воды."; deriv="morruunae, morruunsha"}
$entries += @{id="L-000193"; lex="koss-ruun"; pos="существительное"; trans="северный народ (лёд-народ)"; etym="koss- (лёд) + ruun- (народ)"; ex1="Koss-ruun kossi thero."; ex1t="Северный народ живёт во льдах."; ex2="Koss-ruun thel xara."; ex2t="Народ холода знает цену жизни."; deriv="kossruunae, kossruunsha"}
$entries += @{id="L-000194"; lex="kel-ruun"; pos="существительное"; trans="горный народ (высота-народ)"; etym="kel- (высота) + ruun- (народ)"; ex1="Kel-ruun kel-ver thero."; ex1t="Горный народ живёт в хребтах."; ex2="Kel-ruun veri veno."; ex2t="Верховцы знают каждую скалу."; deriv="kelruunae, kelruunsha"}
$entries += @{id="L-000195"; lex="ven-ruun"; pos="существительное"; trans="народ знания, учёные (знание-народ)"; etym="ven- (знание) + ruun- (народ)"; ex1="Ven-ruun veni thero."; ex1t="Народ знания собирается в библиотеках."; ex2="Ven-ruun thel veno."; ex2t="Учёные — хранители истины."; deriv="venruunae, venruunveni"}
$entries += @{id="L-000196"; lex="vex-kel"; pos="существительное"; trans="энергия высоты, потенциальная энергия (сила-высота)"; etym="vex- (сила) + kel- (высота)"; ex1="Vex-kel keli thero."; ex1t="Энергия высоты — на вершине."; ex2="Vex-kel thel vexi."; ex2t="Потенциал готов высвободиться."; deriv="vexkelae, vexkelvashi"}
$entries += @{id="L-000197"; lex="khar-vash"; pos="существительное"; trans="солнечный камень, янтарь (свет-камень)"; etym="khar- (свет) + vash- (камень)"; ex1="Khar-vash thel kharu."; ex1t="Янтарь хранит свет."; ex2="Khar-vash thel vasha."; ex2t="Солнечный камень твёрд как свет."; deriv="kharvashae, kharvashxari"}
$entries += @{id="L-000198"; lex="ven-mor"; pos="существительное"; trans="глубинное знание, тайна (истина-вода)"; etym="ven- (истина) + mor- (вода)"; ex1="Ven-mor mori thero."; ex1t="Глубинное знание — под водой."; ex2="Ven-mor thel xha."; ex2t="Тайна ждёт разума."; deriv="venmorae, venmorveni"}
$entries += @{id="L-000199"; lex="sha-vex"; pos="существительное"; trans="заклинание, слово-сила (слово-сила)"; etym="sha- (слово) + vex- (сила)"; ex1="Sha-vex ruuni thero."; ex1t="Слово-сила ведёт народ."; ex2="Sha-vex thel vexo."; ex2t="Заклинание — действие словом."; deriv="shavexae, shavexxhare"}
$entries += @{id="L-000200"; lex="xha-zhal"; pos="существительное"; trans="мысль, унесённая ветром, намёк (разум-воздух)"; etym="xha- (разум) + zhal- (воздух)"; ex1="Xha-zhal thali thero."; ex1t="Намёк летит по ветру."; ex2="Xha-zhal thel sharu."; ex2t="Мысль-ветер — невысказанное слово."; deriv="xhazhalae, xhazhalxhare"}

# 201-250: More nature & landscape compounds
$entries += @{id="L-000201"; lex="the-kel"; pos="существительное"; trans="плато, плоскогорье (земля-высота)"; etym="the- (земля) + kel- (высота)"; ex1="The-kel thali thero."; ex1t="Плато поднимается к горизонту."; ex2="The-kel thel the-rass."; ex2t="Плоскогорье — высокая равнина."; deriv="thekelae, thekelxare"}
$entries += @{id="L-000202"; lex="mor-khar"; pos="существительное"; trans="морская звезда,生物 (вода-свет)"; etym="mor- (вода) + khar- (свет)"; ex1="Mor-khar mori thero."; ex1t="Морская звезда живёт в воде."; ex2="Mor-khar thel xarae."; ex2t="Свет воды — живой."; deriv="morkharae, morkharxare"}
$entries += @{id="L-000203"; lex="vokh-thal"; pos="существительное"; trans="ясное небо, спокойствие (порядок-небо)"; etym="vokh- (порядок) + thal- (небо)"; ex1="Vokh-thal thali thero."; ex1t="Ясное небо до горизонта."; ex2="Vokh-thal thel vokhra."; ex2t="Спокойствие — гармония неба."; deriv="vokhthalae, vokhthalxare"}
$entries += @{id="L-000204"; lex="koss-vex"; pos="существительное"; trans="криоэнергия, сила холода (лёд-сила)"; etym="koss- (лёд) + vex- (сила)"; ex1="Koss-vex kossi thero."; ex1t="Сила холода — в леднике."; ex2="Koss-vex thel vexa."; ex2t="Холод — великая энергия."; deriv="kossvexae, kossvexvashi"}
$entries += @{id="L-000205"; lex="zhal-ver"; pos="существительное"; trans="облако над горой (воздух-гора)"; etym="zhal- (воздух) + ver- (гора)"; ex1="Zhal-ver keli thero."; ex1t="Облако обнимает вершину."; ex2="Zhal-ver thel thal-ver."; ex2t="Небесная гора — облако."; deriv="zhalverae, zhalverxari"}
$entries += @{id="L-000206"; lex="sha-koss"; pos="существительное"; trans="молчание, застывшее слово (слово-лёд)"; etym="sha- (слово) + koss- (лёд)"; ex1="Sha-koss xhari thero."; ex1t="Молчание застывает в разуме."; ex2="Sha-koss thel sharu."; ex2t="Ледяное слово — несказанное."; deriv="shakossae, shakossxhare"}
$entries += @{id="L-000207"; lex="vex-ven"; pos="существительное"; trans="доказательство, сила истины (сила-истина)"; etym="vex- (сила) + ven- (истина)"; ex1="Vex-ven xhari thero."; ex1t="Сила истины утверждается разумом."; ex2="Vex-ven thel vena."; ex2t="Доказательство — победа истины."; deriv="vexvenae, vexvenvene"}
$entries += @{id="L-000208"; lex="the-ver"; pos="существительное"; trans="подножие горы (земля-гора)"; etym="the- (земля) + ver- (гора)"; ex1="The-ver veri theri."; ex1t="Подножие у скалы."; ex2="The-ver ruuni thero."; ex2t="У подножия — поселение."; deriv="theverae, theverxari"}
$entries += @{id="L-000209"; lex="khar-rass"; pos="существительное"; trans="галактика, свет-пространство (свет-пространство)"; etym="khar- (свет) + rass- (пространство)"; ex1="Khar-rass thal-rass thero."; ex1t="Галактика сияет в космосе."; ex2="Khar-rass thel rhuri."; ex2t="Галактика — огромный свет."; deriv="kharassae, kharassvene"}
$entries += @{id="L-000210"; lex="xha-ver"; pos="существительное"; trans="твёрдая идея, убеждение (разум-гора)"; etym="xha- (разум) + ver- (гора)"; ex1="Xha-ver xhari thero."; ex1t="Убеждение крепко в разуме."; ex2="Xha-ver thel vera."; ex2t="Твёрдая идея несокрушима."; deriv="xhaverae, xhaverxhare"}

$entries += @{id="L-000211"; lex="ruun-rass"; pos="существительное"; trans="диаспора, народ в пространстве (народ-пространство)"; etym="ruun- (народ) + rass- (пространство)"; ex1="Ruun-rass thali thero."; ex1t="Диаспора рассеяна по миру."; ex2="Ruun-rass thel sha-ruun."; ex2t="Народ вдали хранит язык."; deriv="ruunrassae, ruunrasssha"}
$entries += @{id="L-000212"; lex="vash-vex"; pos="существительное"; trans="тектоническая сила (камень-сила)"; etym="vash- (камень) + vex- (сила)"; ex1="Vash-vex theri thero."; ex1t="Тектоническая сила движет землёй."; ex2="Vash-vex thel vexa."; ex2t="Сила камня — в его мощи."; deriv="vashvexae, vashvexxari"}
$entries += @{id="L-000213"; lex="thal-ser"; pos="существительное"; trans="ночное светило, луна (небо-спутник)"; etym="thal- (небо) + ser- (спутник)"; ex1="Thal-ser thali thero."; ex1t="Луна всходит к горизонту."; ex2="Thal-ser thel sera."; ex2t="Ночное светило циклично."; deriv="thalserae, thalserven"}
$entries += @{id="L-000214"; lex="mor-ven"; pos="существительное"; trans="гидрология, знание о воде (вода-знание)"; etym="mor- (вода) + ven- (знание)"; ex1="Mor-ven mori thero."; ex1t="Гидрология изучает воду."; ex2="Mor-ven thel vena."; ex2t="Знание о воде — истина."; deriv="morvenae, morvenvene"}
$entries += @{id="L-000215"; lex="khar-xha"; pos="существительное"; trans="просветление (свет-разум)"; etym="khar- (свет) + xha- (разум)"; ex1="Khar-xha xhari thero."; ex1t="Просветление озаряет разум."; ex2="Khar-xha thel xhara."; ex2t="Свет разума — высшая мудрость."; deriv="kharxharae, kharxhaxhare"}
$entries += @{id="L-000216"; lex="the-ser"; pos="существительное"; trans="климат, земной цикл (земля-цикл)"; etym="the- (земля) + ser- (цикл)"; ex1="The-ser theri thero."; ex1t="Климат меняет землю."; ex2="The-ser thel xaro."; ex2t="Земной цикл — основа жизни."; deriv="theserae, theservene"}
$entries += @{id="L-000217"; lex="ven-khar"; pos="существительное"; trans="откровение (истина-свет)"; etym="ven- (истина) + khar- (свет)"; ex1="Ven-khar xhari thero."; ex1t="Откровение озаряет разум."; ex2="Ven-khar thel sharu."; ex2t="Истинный свет рождает слово."; deriv="venkharae, venkharxhare"}
$entries += @{id="L-000218"; lex="sha-xha"; pos="существительное"; trans="лингвистика, наука о языке (слово-разум)"; etym="sha- (слово) + xha- (разум)"; ex1="Sha-xha xhari thero."; ex1t="Лингвистика — разум слова."; ex2="Sha-xha thel shara."; ex2t="Наука о языке — система."; deriv="shaxharae, shaxhavene"}
$entries += @{id="L-000219"; lex="vokh-ven"; pos="существительное"; trans="система знаний, таксономия (порядок-знание)"; etym="vokh- (порядок) + ven- (знание)"; ex1="Vokh-ven veni thero."; ex1t="Таксономия живёт в архивах."; ex2="Vokh-ven thel vokhra."; ex2t="Система знаний — это порядок."; deriv="vokhvenae, vokhvenvene"}
$entries += @{id="L-000220"; lex="koss-ver"; pos="существительное"; trans="заснеженная вершина (лёд-гора)"; etym="koss- (лёд) + ver- (гора)"; ex1="Koss-ver thali thero."; ex1t="Снежная шапка белеет вдали."; ex2="Koss-ver thel kossi."; ex2t="Вершина скована льдом."; deriv="kossverae, kossverxari"}

# 221-250: More compounds
$entries += @{id="L-000221"; lex="zhal-ven"; pos="существительное"; trans="слух, непроверенная информация (воздух-истина)"; etym="zhal- (воздух) + ven- (истина)"; ex1="Zhal-ven ruuni thero."; ex1t="Слух летит по народу."; ex2="Zhal-ven thel vena?"; ex2t="Слух — истина или нет?"; deriv="zhalvenae, zhalvenxhare"}
$entries += @{id="L-000222"; lex="xha-kel"; pos="существительное"; trans="амбиция, высота мысли (разум-высота)"; etym="xha- (разум) + kel- (высота)"; ex1="Xha-kel xhari thero."; ex1t="Мысль стремится ввысь."; ex2="Xha-kel thel keli."; ex2t="Амбиция достигает вершины."; deriv="xhakelae, xhakelxhare"}
$entries += @{id="L-000223"; lex="vex-zhal"; pos="существительное"; trans="электричество, сила воздуха (сила-воздух)"; etym="vex- (сила) + zhal- (воздух)"; ex1="Vex-zhal thali thero."; ex1t="Электричество сверкает в небе."; ex2="Vex-zhal thel vexi."; ex2t="Сила воздуха — источник энергии."; deriv="vexzhalae, vexzhalvashi"}
$entries += @{id="L-000224"; lex="mor-the"; pos="существительное"; trans="подземные воды (вода-земля)"; etym="mor- (вода) + the- (земля)"; ex1="Mor-the theri thero."; ex1t="Вода течёт под землёй."; ex2="Mor-the thel xari."; ex2t="Подземные воды питают жизнь."; deriv="mortherae, mortheven"}
$entries += @{id="L-000225"; lex="khar-kel"; pos="существительное"; trans="маяк, свет высоты (свет-высота)"; etym="khar- (свет) + kel- (высота)"; ex1="Khar-kel thali thero."; ex1t="Маяк сияет у горизонта."; ex2="Khar-kel thel khari."; ex2t="Высокий свет — ориентир."; deriv="kharkelae, kharkelkoss"}
$entries += @{id="L-000226"; lex="ruun-vokh"; pos="существительное"; trans="общественный строй (народ-порядок)"; etym="ruun- (народ) + vokh- (порядок)"; ex1="Ruun-vokh ruuni theri."; ex1t="Общественный строй держит народ."; ex2="Ruun-vokh thel vokhra."; ex2t="Строй — основа порядка."; deriv="ruunvokhrae, ruunvokhre"}
$entries += @{id="L-000227"; lex="vash-ser"; pos="существительное"; trans="каменный круг, мегалит (камень-цикл)"; etym="vash- (камень) + ser- (цикл)"; ex1="Vash-ser thali thero."; ex1t="Каменный круг стоит веками."; ex2="Vash-ser thel sera."; ex2t="Мегалит отмечает циклы."; deriv="vashserae, vashserven"}
$entries += @{id="L-000228"; lex="thal-ven"; pos="существительное"; trans="астрология (небо-знание)"; etym="thal- (небо) + ven- (знание)"; ex1="Thal-ven thali thero."; ex1t="Астрология читает небо."; ex2="Thal-ven khar-vex veno."; ex2t="Небесное знание о звёздах."; deriv="thalvenae, thalvenvene"}
$entries += @{id="L-000229"; lex="xha-ver"; pos="существительное"; trans="упрямство, твёрдая воля (разум-гора)"; etym="xha- (разум) + ver- (гора)"; ex1="Xha-ver xhari thero."; ex1t="Упрямство — гора в разуме."; ex2="Xha-ver thel vera."; ex2t="Твёрдая воля несокрушима."; deriv="xhaverae, xhaverxhare"}
$entries += @{id="L-000230"; lex="khar-ven"; pos="существительное"; trans="прозрение (свет-истина)"; etym="khar- (свет) + ven- (истина)"; ex1="Khar-ven xhari thero."; ex1t="Прозрение озаряет разум."; ex2="Khar-ven thel vena."; ex2t="Свет истины — знание."; deriv="kharvenae, kharvenvene"}

$entries += @{id="L-000231"; lex="zhal-ver"; pos="существительное"; trans="ветер в горах (воздух-гора)"; etym="zhal- (воздух) + ver- (гора)"; ex1="Zhal-ver veri thero."; ex1t="Ветер гудит в скалах."; ex2="Zhal-ver thel zhalo."; ex2t="Горный ветер — дыхание."; deriv="zhalverae, zhalverxare"}
$entries += @{id="L-000232"; lex="koss-xha"; pos="существительное"; trans="медитация, холод разума (лёд-разум)"; etym="koss- (лёд) + xha- (разум)"; ex1="Koss-xha xhari thero."; ex1t="Медитация замораживает мысли."; ex2="Koss-xha thel vokhra."; ex2t="Холодный разум — порядок."; deriv="kossxharae, kossxhaxhare"}
$entries += @{id="L-000233"; lex="ven-zhal"; pos="существительное"; trans="очевидность, ясность (истина-воздух)"; etym="ven- (истина) + zhal- (воздух)"; ex1="Ven-zhal xhari thero."; ex1t="Ясность — в разуме."; ex2="Ven-zhal thel vena."; ex2t="Очевидность — истина в воздухе."; deriv="venzhalae, venzhalxhare"}
$entries += @{id="L-000234"; lex="sha-ver"; pos="существительное"; trans="клятва, слово твёрдое как скала (слово-гора)"; etym="sha- (слово) + ver- (гора)"; ex1="Sha-ver ruuni theri."; ex1t="Клятва скрепляет народ."; ex2="Sha-ver thel vera."; ex2t="Слово твёрже камня."; deriv="shaverae, shaverxhare"}
$entries += @{id="L-000235"; lex="mor-vash"; pos="существительное"; trans="риф, подводный камень (вода-камень)"; etym="mor- (вода) + vash- (камень)"; ex1="Mor-vash mori thero."; ex1t="Риф скрыт под водой."; ex2="Mor-vash thel vasha."; ex2t="Подводный камень твёрд."; deriv="morvashae, morvashxari"}
$entries += @{id="L-000236"; lex="khar-the"; pos="существительное"; trans="поверхность, освещённая земля (свет-земля)"; etym="khar- (свет) + the- (земля)"; ex1="Khar-the theri thero."; ex1t="Свет освещает землю."; ex2="Khar-the thel xaro."; ex2t="Освещённая земля полна жизни."; deriv="khartherae, khartherxare"}
$entries += @{id="L-000237"; lex="ruun-khar"; pos="существительное"; trans="слава, величие народа (народ-свет)"; etym="ruun- (народ) + khar- (свет)"; ex1="Ruun-khar thali thero."; ex1t="Слава народа сияет вдали."; ex2="Ruun-khar thel khara."; ex2t="Величие — свет народа."; deriv="ruunkharae, ruunkharxhare"}
$entries += @{id="L-000238"; lex="vex-the"; pos="существительное"; trans="геотермальный источник (сила-земля)"; etym="vex- (сила) + the- (земля)"; ex1="Vex-the theri thero."; ex1t="Геотермальный источник бьёт из земли."; ex2="Vex-the thel vexi."; ex2t="Земная сила — источник."; deriv="vextherae, vexthevashi"}
$entries += @{id="L-000239"; lex="zhal-thal"; pos="существительное"; trans="стратосфера (воздух-небо)"; etym="zhal- (воздух) + thal- (небо)"; ex1="Zhal-thal thali thero."; ex1t="Стратосфера — высокое небо."; ex2="Zhal-thal thel zhali."; ex2t="Верхний слой — граница."; deriv="zhalthalae, zhalthalxari"}
$entries += @{id="L-000240"; lex="vokh-xha"; pos="существительное"; trans="дисциплина ума (порядок-разум)"; etym="vokh- (порядок) + xha- (разум)"; ex1="Vokh-xha xhari thero."; ex1t="Дисциплина организует разум."; ex2="Vokh-xha thel veno."; ex2t="Порядок ума ведёт к знанию."; deriv="vokhxharae, vokhxhaxhare"}

$entries += @{id="L-000241"; lex="sha-zhal"; pos="существительное"; trans="шепот, воздушное слово (слово-воздух)"; etym="sha- (слово) + zhal- (воздух)"; ex1="Sha-zhal thali thero."; ex1t="Шёпот летит по ветру."; ex2="Sha-zhal thel zhal-ven."; ex2t="Слово-ветер — неподтверждённое."; deriv="shazhalae, shazhalxhare"}
$entries += @{id="L-000242"; lex="xha-ruun"; pos="существительное"; trans="цивилизация (разум-народ)"; etym="xha- (разум) + ruun- (народ)"; ex1="Xha-ruun thali thero."; ex1t="Цивилизация смотрит в небо."; ex2="Xha-ruun thel shara."; ex2t="Разумный народ имеет язык."; deriv="xharuunae, xharuunven"}
$entries += @{id="L-000243"; lex="khar-zhal"; pos="существительное"; trans="радуга (свет-воздух)"; etym="khar- (свет) + zhal- (воздух)"; ex1="Khar-zhal thali thero."; ex1t="Радуга — мост в небе."; ex2="Khar-zhal thel khar-mor."; ex2t="Свет и воздух рождают цвета."; deriv="kharzhalae, kharzhalxari"}
$entries += @{id="L-000244"; lex="ruun-zhal"; pos="существительное"; trans="молва (народ-воздух)"; etym="ruun- (народ) + zhal- (воздух)"; ex1="Ruun-zhal ruuni thero."; ex1t="Молва летит по народу."; ex2="Ruun-zhal thel zhal-ven."; ex2t="Молва — воздух без истины."; deriv="ruunzhalae, ruunzhalxhare"}
$entries += @{id="L-000245"; lex="vex-ver"; pos="существительное"; trans="оползень, камнепад (сила-гора)"; etym="vex- (сила) + ver- (гора)"; ex1="Vex-ver veri thero."; ex1t="Камнепад сходит со скалы."; ex2="Vex-ver thel vexa."; ex2t="Гора обрушивается с силой."; deriv="vexverae, vexvervash"}
$entries += @{id="L-000246"; lex="vokh-mor"; pos="существительное"; trans="спокойная вода, штиль (порядок-вода)"; etym="vokh- (порядок) + mor- (вода)"; ex1="Vokh-mor mor-thal thero."; ex1t="Штиль на океане."; ex2="Vokh-mor thel vokhra."; ex2t="Спокойная вода — гармония."; deriv="vokhmorae, vokhmorven"}
$entries += @{id="L-000247"; lex="xha-thel"; pos="существительное"; trans="догадка, малая мысль (разум-малый)"; etym="xha- (разум) + thel- (малый)"; ex1="Xha-thel xhari thero."; ex1t="Догадка мелькает в разуме."; ex2="Xha-thel thel xharu."; ex2t="Малая мысль — зерно идеи."; deriv="xhathelae, xhathelxhare"}
$entries += @{id="L-000248"; lex="ven-rass"; pos="существительное"; trans="философия, мировоззрение (истина-пространство)"; etym="ven- (истина) + rass- (пространство)"; ex1="Ven-rass xhari thero."; ex1t="Мировоззрение — в разуме."; ex2="Ven-rass thel vena."; ex2t="Философия ищет истину."; deriv="venrassae, venrassvene"}
$entries += @{id="L-000249"; lex="sha-khar"; pos="существительное"; trans="откровение, слово света (слово-свет)"; etym="sha- (слово) + khar- (свет)"; ex1="Sha-khar xhari thero."; ex1t="Откровение озаряет разум."; ex2="Sha-khar thel shara."; ex2t="Слово света — высшая речь."; deriv="shakharae, shakharxhare"}
$entries += @{id="L-000250"; lex="koss-ser"; pos="существительное"; trans="ледяной цикл, эпоха оледенения (лёд-цикл)"; etym="koss- (лёд) + ser- (цикл)"; ex1="Koss-ser thel sera."; ex1t="Ледяной цикл — эпоха."; ex2="Koss-ser kossi thero."; ex2t="Цикл холода меняет мир."; deriv="kossserae, kossserven"}

# 251-300: More compounds
$entries += @{id="L-000251"; lex="xha-vex"; pos="существительное"; trans="сила воли (разум-сила)"; etym="xha- (разум) + vex- (сила)"; ex1="Xha-vex xhari thero."; ex1t="Воля живёт в разуме."; ex2="Xha-vex thel vexo."; ex2t="Сила воли движет действием."; deriv="xhavexae, xhavexxhare"}
$entries += @{id="L-000252"; lex="kel-thal"; pos="существительное"; trans="высокогорное плато (высота-небо)"; etym="kel- (высота) + thal- (небо)"; ex1="Kel-thal thali thero."; ex1t="Плато у неба."; ex2="Kel-thal thel the-rass."; ex2t="Высокогорная равнина."; deriv="kelthalae, kelthalxari"}
$entries += @{id="L-000253"; lex="mor-rass"; pos="существительное"; trans="морской простор (вода-пространство)"; etym="mor- (вода) + rass- (пространство)"; ex1="Mor-rass mor-thal thero."; ex1t="Морской простор — океан."; ex2="Mor-rass thel rhuri."; ex2t="Водный простор велик."; deriv="morrassae, morrassvene"}
$entries += @{id="L-000254"; lex="vash-zhal"; pos="существительное"; trans="скала, обдуваемая ветром (камень-воздух)"; etym="vash- (камень) + zhal- (воздух)"; ex1="Vash-zhal thali thero."; ex1t="Ветер точит камень."; ex2="Vash-zhal thel zhalo."; ex2t="Камень дышит ветром."; deriv="vashzhalae, vashzhalxari"}
$entries += @{id="L-000255"; lex="xha-rass"; pos="существительное"; trans="ментальное пространство (разум-пространство)"; etym="xha- (разум) + rass- (пространство)"; ex1="Xha-rass thali thero."; ex1t="Разум создаёт миры."; ex2="Xha-rass thel xharu."; ex2t="В пространстве мысли — идеи."; deriv="xharassae, xharassvene"}
$entries += @{id="L-000256"; lex="khar-ruun"; pos="существительное"; trans="народ света, просвещённый народ (свет-народ)"; etym="khar- (свет) + ruun- (народ)"; ex1="Khar-ruun thali thero."; ex1t="Просвещённый народ идёт к свету."; ex2="Khar-ruun thel vena."; ex2t="Народ света чтит истину."; deriv="kharruunae, kharruunven"}
$entries += @{id="L-000257"; lex="vash-rass"; pos="существительное"; trans="каменная пустыня (камень-пространство)"; etym="vash- (камень) + rass- (пространство)"; ex1="Vash-rass thali thero."; ex1t="Пустыня до горизонта."; ex2="Vash-rass thel xari."; ex2t="Каменное пространство — среда."; deriv="vashrassae, vashrassxari"}
$entries += @{id="L-000258"; lex="zhal-rass"; pos="существительное"; trans="воздушное пространство (воздух-пространство)"; etym="zhal- (воздух) + rass- (пространство)"; ex1="Zhal-rass thali thero."; ex1t="Воздушное пространство — небо."; ex2="Zhal-rass thel zhali."; ex2t="Пространство воздуха — атмосфера."; deriv="zhalrassae, zhalrassvene"}
$entries += @{id="L-000259"; lex="sha-ven"; pos="существительное"; trans="точное знание (слово-истина)"; etym="sha- (слово) + ven- (истина)"; ex1="Sha-ven xhari thero."; ex1t="Точное знание — в разуме."; ex2="Sha-ven thel vena."; ex2t="Слово истины — точность."; deriv="shavenae, shavenvene"}
$entries += @{id="L-000260"; lex="vex-koss"; pos="существительное"; trans="сила холода (сила-лёд)"; etym="vex- (сила) + koss- (лёд)"; ex1="Vex-koss kossi thero."; ex1t="Сила холода в леднике."; ex2="Vex-koss thel vexa."; ex2t="Мороз — могучая сила."; deriv="vexkossae, vexkossvash"}

$entries += @{id="L-000261"; lex="the-vokh"; pos="существительное"; trans="экосистема (земля-порядок)"; etym="the- (земля) + vokh- (порядок)"; ex1="The-vokh theri thero."; ex1t="Экосистема — порядок земли."; ex2="The-vokh thel xari."; ex2t="Баланс жизни — в земле."; deriv="thevokhrae, thevokhxari"}
$entries += @{id="L-000262"; lex="mor-xha"; pos="существительное"; trans="интуиция (вода-разум)"; etym="mor- (вода) + xha- (разум)"; ex1="Mor-xha xhari thero."; ex1t="Интуиция течёт в разуме."; ex2="Mor-xha thel veno."; ex2t="Чутьё ведёт к знанию."; deriv="morxharae, morxhaxhare"}
$entries += @{id="L-000263"; lex="khar-ser"; pos="существительное"; trans="день и ночь, световой цикл (свет-цикл)"; etym="khar- (свет) + ser- (цикл)"; ex1="Khar-ser thel sera."; ex1t="Цикл света — вечен."; ex2="Khar-ser thel xaro."; ex2t="Смена дня и ночи — жизнь."; deriv="kharserae, kharserven"}
$entries += @{id="L-000264"; lex="ruun-xha"; pos="существительное"; trans="коллективный разум (народ-разум)"; etym="ruun- (народ) + xha- (разум)"; ex1="Ruun-xha ruuni thero."; ex1t="Коллективный разум ведёт народ."; ex2="Ruun-xha thel xhara."; ex2t="Мудрость народа — разумность."; deriv="ruunxharae, ruunxhaxhare"}
$entries += @{id="L-000265"; lex="sha-ver"; pos="существительное"; trans="обет, твёрдое слово (слово-гора)"; etym="sha- (слово) + ver- (гора)"; ex1="Sha-ver ruuni theri."; ex1t="Обет скрепляет народ."; ex2="Sha-ver thel vera."; ex2t="Слово твёрже скалы."; deriv="shaverae, shaverxhare"}
$entries += @{id="L-000266"; lex="ven-vex"; pos="существительное"; trans="несомненная истина (истина-сила)"; etym="ven- (истина) + vex- (сила)"; ex1="Ven-vex xhari thero."; ex1t="Сила истины — в разуме."; ex2="Ven-vex thel vena."; ex2t="Несомненность — абсолютная сила."; deriv="venvexae, venvexvene"}
$entries += @{id="L-000267"; lex="vokh-zhal"; pos="существительное"; trans="спокойствие, ясность (порядок-воздух)"; etym="vokh- (порядок) + zhal- (воздух)"; ex1="Vokh-zhal xhari thero."; ex1t="Ясность наполняет разум."; ex2="Vokh-zhal thel vokhra."; ex2t="Спокойствие — порядок воздуха."; deriv="vokhzhalae, vokhzalxare"}
$entries += @{id="L-000268"; lex="kel-vex"; pos="существительное"; trans="высотная энергия (высота-сила)"; etym="kel- (высота) + vex- (сила)"; ex1="Kel-vex keli thero."; ex1t="На высоте — энергия."; ex2="Kel-vex thel vexi."; ex2t="Высота — источник силы."; deriv="kelvexae, kelvexvashi"}
$entries += @{id="L-000269"; lex="xha-khar"; pos="существительное"; trans="озарение (разум-свет)"; etym="xha- (разум) + khar- (свет)"; ex1="Xha-khar xhari thero."; ex1t="Озарение — свет в разуме."; ex2="Xha-khar thel xharu."; ex2t="Идея рождается из света."; deriv="xhakharrae, xhakharxhare"}
$entries += @{id="L-000270"; lex="mor-khar"; pos="существительное"; trans="отражение луны в воде (вода-свет)"; etym="mor- (вода) + khar- (свет)"; ex1="Mor-khar mori thero."; ex1t="Луна отражается в воде."; ex2="Mor-khar thel ser-thal."; ex2t="Свет воды — от неба."; deriv="morkharae, morkharxari"}

$entries += @{id="L-000271"; lex="thala-rass"; pos="прилагательное"; trans="бескрайний, безграничный"; etym="thal- (небо) + -ae (свойство) + rass- (пространство)"; ex1="Thala-rass thel rhuri."; ex1t="Бескрайнее — великий простор."; ex2="Thala-rass xhari thero."; ex2t="Безграничное рождает мысль."; deriv="-"}
$entries += @{id="L-000272"; lex="vena-mor"; pos="существительное"; trans="кристальная правда"; etym="ven- (истина) + -ae + mor- (вода)"; ex1="Vena-mor xhari thero."; ex1t="Правда чиста как вода."; ex2="Vena-mor thel ven-sha."; ex2t="Кристальная правда — истинное слово."; deriv="-"}
$entries += @{id="L-000273"; lex="khar-vash"; pos="существительное"; trans="кремень, огниво (свет-камень)"; etym="khar- (свет) + vash- (камень)"; ex1="Khar-vash thel vexo."; ex1t="Кремень высекает огонь."; ex2="Khar-vash thel vasha."; ex2t="Камень света твёрд."; deriv="kharvashae, kharvashxari"}
$entries += @{id="L-000274"; lex="zal-vex"; pos="существительное"; trans="воздушный поток, струя (воздух-сила)"; etym="zhal- (воздух) + vex- (сила)"; ex1="Zhal-vex thali thero."; ex1t="Струя воздуха у горизонта."; ex2="Zhal-vex thel vexo."; ex2t="Поток — движение силы."; deriv="zhalvexae"}
$entries += @{id="L-000275"; lex="xha-vokh"; pos="существительное"; trans="ментальная гармония (разум-порядок)"; etym="xha- (разум) + vokh- (порядок)"; ex1="Xha-vokh xhari thero."; ex1t="Гармония в разуме."; ex2="Xha-vokh thel vokhra."; ex2t="Ментальный порядок — баланс."; deriv="xhavokhrae"}
$entries += @{id="L-000276"; lex="the-mor"; pos="существительное"; trans="болото (земля-вода)"; etym="the- (земля) + mor- (вода)"; ex1="The-mor theri thero."; ex1t="Болото — вода на земле."; ex2="The-mor thel xari."; ex2t="Трясина — особая среда."; deriv="themorae, themorxare"}
$entries += @{id="L-000277"; lex="sha-ven"; pos="существительное"; trans="доказательство, верное слово (слово-истина)"; etym="sha- (слово) + ven- (истина)"; ex1="Sha-ven xhari thero."; ex1t="Доказательство — в разуме."; ex2="Sha-ven thel vena."; ex2t="Верное слово — истина."; deriv="shavenae, shavenvene"}
$entries += @{id="L-000278"; lex="kel-vokh"; pos="существительное"; trans="иерархия (высота-порядок)"; etym="kel- (высота) + vokh- (порядок)"; ex1="Kel-vokh ruuni theri."; ex1t="Иерархия организует народ."; ex2="Kel-vokh thel vokhra."; ex2t="Порядок высот — структура."; deriv="kelvokhrae, kelvokhre"}
$entries += @{id="L-000279"; lex="ven-ver"; pos="существительное"; trans="непреложная истина (истина-гора)"; etym="ven- (истина) + ver- (гора)"; ex1="Ven-ver xhari thero."; ex1t="Истина — гора в разуме."; ex2="Ven-ver thel vera."; ex2t="Непреложность несокрушима."; deriv="venverae, venvervene"}
$entries += @{id="L-000280"; lex="vex-khar"; pos="существительное"; trans="искра (сила-свет)"; etym="vex- (сила) + khar- (свет)"; ex1="Vex-khar thel vexi."; ex1t="Искра — источник света."; ex2="Vex-khar thel kharu."; ex2t="Сила рождает свет."; deriv="vexkharae, vexkharxari"}

$entries += @{id="L-000281"; lex="koss-ven"; pos="существительное"; trans="застывшая истина, догма (лёд-истина)"; etym="koss- (лёд) + ven- (истина)"; ex1="Koss-ven xhari thero."; ex1t="Догма застыла в разуме."; ex2="Koss-ven thel kossa."; ex2t="Застывшая истина холодна."; deriv="kossvenae, kossvenvene"}
$entries += @{id="L-000282"; lex="xha-sha"; pos="существительное"; trans="смысл, значение (разум-слово)"; etym="xha- (разум) + sha- (слово)"; ex1="Xha-sha xhari thero."; ex1t="Смысл рождается в разуме."; ex2="Xha-sha thel sharu."; ex2t="Значение слова — в мысли."; deriv="xhasharae, xhashavene"}
$entries += @{id="L-000283"; lex="mor-vash"; pos="существительное"; trans="коралл (вода-камень)"; etym="mor- (вода) + vash- (камень)"; ex1="Mor-vash mori thero."; ex1t="Коралл растёт в воде."; ex2="Mor-vash thel xari."; ex2t="Коралл — среда жизни."; deriv="morvashae, morvashxare"}
$entries += @{id="L-000284"; lex="zhal-khar"; pos="существительное"; trans="сухой туман, дымка (воздух-свет)"; etym="zhal- (воздух) + khar- (свет)"; ex1="Zhal-khar thali thero."; ex1t="Дымка у горизонта."; ex2="Zhal-khar thel khar-zhal."; ex2t="Воздух и свет — мираж."; deriv="zhalkharae, zhalkharxari"}
$entries += @{id="L-000285"; lex="ruun-ver"; pos="существительное"; trans="оплот народа (народ-гора)"; etym="ruun- (народ) + ver- (гора)"; ex1="Ruun-ver ruuni theri."; ex1t="Оплот защищает народ."; ex2="Ruun-ver thel vera."; ex2t="Народ-гора несокрушим."; deriv="ruunverae, ruunvervash"}
$entries += @{id="L-000286"; lex="vex-rass"; pos="существительное"; trans="энергетическое поле (сила-пространство)"; etym="vex- (сила) + rass- (пространство)"; ex1="Vex-rass thali thero."; ex1t="Поле силы простирается."; ex2="Vex-rass thel vexa."; ex2t="Пространство силы — мощь."; deriv="vexrassae, vexrassvashi"}
$entries += @{id="L-000287"; lex="vokh-kel"; pos="существительное"; trans="совершенство (порядок-высота)"; etym="vokh- (порядок) + kel- (высота)"; ex1="Vokh-kel xhari thero."; ex1t="Совершенство — высота порядка."; ex2="Vokh-kel thel vokhra."; ex2t="Гармония на высоте."; deriv="vokhkelae, vokhkelxhare"}
$entries += @{id="L-000288"; lex="xha-the"; pos="существительное"; trans="здравый смысл (разум-земля)"; etym="xha- (разум) + the- (земля)"; ex1="Xha-the xhari thero."; ex1t="Здравый смысл — земля разума."; ex2="Xha-the thel thera."; ex2t="Практичность — земность мысли."; deriv="xhatherae, xhatheven"}
$entries += @{id="L-000289"; lex="ser-ven"; pos="существительное"; trans="цикл познания (цикл-истина)"; etym="ser- (цикл) + ven- (истина)"; ex1="Ser-ven xhari thero."; ex1t="Познание циклично."; ex2="Ser-ven thel sera."; ex2t="Цикл истины — вечен."; deriv="servenae, servenvene"}
$entries += @{id="L-000290"; lex="khar-mor"; pos="существительное"; trans="блик (свет-вода)"; etym="khar- (свет) + mor- (вода)"; ex1="Khar-mor mori thero."; ex1t="Блик на воде."; ex2="Khar-mor thel kharu."; ex2t="Свет играет с водой."; deriv="kharmorae, kharmorxari"}

$entries += @{id="L-000291"; lex="sha-the"; pos="существительное"; trans="простой язык, диалект (слово-земля)"; etym="sha- (слово) + the- (земля)"; ex1="Sha-the ruuni thero."; ex1t="Простой язык — народа."; ex2="Sha-the thel shara."; ex2t="Земной язык — основа."; deriv="shatherae, shatheven"}
$entries += @{id="L-000292"; lex="vex-thal"; pos="существительное"; trans="молния (сила-небо)"; etym="vex- (сила) + thal- (небо)"; ex1="Vex-thal thali thero."; ex1t="Молния в небе."; ex2="Vex-thal thel vexa."; ex2t="Небесная сила бьёт."; deriv="vexthalae, vexthalxari"}
$entries += @{id="L-000293"; lex="mor-vash"; pos="существительное"; trans="риф (вода-камень)"; etym="mor- (вода) + vash- (камень)"; ex1="Mor-vash mori thero."; ex1t="Риф под водой."; ex2="Mor-vash thel vasha."; ex2t="Камень в воде твёрд."; deriv="morvashae, morvashxari"}
$entries += @{id="L-000294"; lex="zhal-vash"; pos="существительное"; trans="эрозия (воздух-камень)"; etym="zhal- (воздух) + vash- (камень)"; ex1="Zhal-vash veri thero."; ex1t="Ветер точит скалу."; ex2="Zhal-vash thel zhalo."; ex2t="Воздух разрушает камень."; deriv="zhalvashae, zhalvashxari"}
$entries += @{id="L-000295"; lex="ven-xha"; pos="существительное"; trans="философия (истина-разум)"; etym="ven- (истина) + xha- (разум)"; ex1="Ven-xha xhari thero."; ex1t="Философия — истина разума."; ex2="Ven-xha thel veno."; ex2t="Мудрость познаётся."; deriv="venxharae, venxhaxhare"}
$entries += @{id="L-000296"; lex="koss-ven"; pos="существительное"; trans="догма (лёд-истина)"; etym="koss- (лёд) + ven- (истина)"; ex1="Koss-ven xhari thero."; ex1t="Догма застыла."; ex2="Koss-ven thel kossa."; ex2t="Истина без движения."; deriv="kossvenae, kossvenvene"}
$entries += @{id="L-000297"; lex="xha-ver"; pos="существительное"; trans="убеждение (разум-гора)"; etym="xha- (разум) + ver- (гора)"; ex1="Xha-ver xhari thero."; ex1t="Убеждение — гора в мысли."; ex2="Xha-ver thel vera."; ex2t="Крепкая вера."; deriv="xhaverae, xhaverxhare"}
$entries += @{id="L-000298"; lex="rath-zhal"; pos="существительное"; trans="вихрь, смерч"; etym="rath- (вращение) + zhal- (воздух)"; ex1="Rath-zhal thali thero."; ex1t="Смерч у горизонта."; ex2="Rath-zhal thel vexa."; ex2t="Вихрь — сила воздуха."; deriv="rathzhalae, rathzhalxari"}
$entries += @{id="L-000299"; lex="mor-thal"; pos="прилагательное"; trans="океанический"; etym="mor- (вода) + thal- (небо) + -ae"; ex1="Mor-thal thel rhuri."; ex1t="Океанское — великое."; ex2="Mor-thal xari thero."; ex2t="Океаническая среда."; deriv="-"}
$entries += @{id="L-000300"; lex="xha-ruun"; pos="прилагательное"; trans="цивилизованный, разумно-народный"; etym="xha- (разум) + ruun- (народ) + -ae"; ex1="Xha-ruun thel shara."; ex1t="Цивилизованное — язык."; ex2="Xha-ruun vokhri thero."; ex2t="Разумный народ чтит храм."; deriv="-"}

# Generate all files
foreach ($e in $entries) {
    $rootFlag = "нет"
    $content = @"
# $($e.id): $($e.lex)

**Корень:** $rootFlag
**Часть речи:** $($e.pos)
**Перевод:** $($e.trans)
**Статус:** active
**Создан:** $date

## Этимология

$($e.etym)

## Примеры

1. $($e.ex1) — $($e.ex1t)
2. $($e.ex2) — $($e.ex2t)

## Производные

$($e.deriv)
"@
    $filePath = Join-Path $basePath "$($e.id).md"
    Set-Content -Path $filePath -Value $content -Encoding UTF8
    Write-Output "Created $($e.id)"
}
